packages/ponder/src/core/indexer/logQueue.ts
Currently the `logWorker` is silently crashing. This is happening because the `stats.sourceStats[source.name]` object is uninitialized. When trying to access a field of this `undefined` object the worker silently fails
=> Initialize `stats` in `LogQueue` to avoid silent crash

.github/workflows/main.yml, package.json, packages/core/jest.config.js, packages/core/package.json, packages/core/src/Ponder.ts, packages/core/src/indexer/tasks/startBackfill.ts, packages/core/src/indexer/tasks/startBackfillForSource.ts, packages/core/src/indexer/tasks/startFrontfill.ts, packages/core/src/plugin/index.ts, packages/core/test/main.test.ts, packages/create-ponder/package.json, packages/graphql/package.json, packages/graphql/src/index.ts, packages/graphql/src/server/index.ts
Changes
- Adds an optional `teardown` method to plugins
- Makes the `Ponder.kill()` method work (process should exit gracefully)
Also
- Add a Lint CI step
=> Improve `Ponder` lifecycle mgmt

docs/pages/api-reference/schema-graphql.mdx, docs/pages/faq/production.mdx, examples/ethfs/render.yaml, packages/core/src/Ponder.ts, packages/core/src/bin/ponder.ts, packages/core/src/cli/codegen.ts, packages/core/src/cli/dev.ts, packages/core/src/cli/start.ts, packages/core/src/codegen/generateHandlerTypes.ts, packages/core/src/codegen/utils.ts, packages/core/src/common/logger.ts, packages/core/src/common/utils.ts, packages/core/src/db/entity/sqliteEntityStore.ts, packages/core/src/handlers/handlerQueue.ts, packages/core/src/handlers/readHandlers.ts, packages/core/src/indexer/tasks/startBackfillForSource.ts, packages/core/src/networks/buildNetworks.ts, packages/core/src/schema/readSchema.ts, packages/core/src/ui/HandlersBar.tsx, packages/core/src/ui/app.tsx, packages/core/test/main.test.ts, packages/create-ponder/src/index.ts, packages/create-ponder/src/templates/etherscan.ts, packages/graphql/src/index.ts, packages/graphql/src/server/index.ts, render.yaml
This PR aims to improve logging and error handling.
- `schema.graphql` is now hot reloaded and schema parsing errors are handled by the dev error handler (shouldn't exit process)
- `ponder dev` displays the dev UI + `event` and `error` messages
- `ponder start` does not display the dev UI but logs `backfill`, `frontfill`, and `indexer` messages
Also
- Fixes a bug where `create-ponder` would not format ABIs downloaded from etherscan
- Renames `POSTGRES_URL` -> `DATABASE_URL` everywhere (for consistency with Railway naming)
- Refactors the `ponder` script to directly init the `Ponder` instance; deletes the `cli/` dir and files in there
=> Improve logs, error handling, and docs polish

packages/core/src/Ponder.ts, packages/core/src/codegen/ethers-abitype/README.md, packages/core/src/codegen/ethers-abitype/contracts.ts, packages/core/src/codegen/ethers-abitype/getContract.ts, packages/core/src/codegen/ethers-abitype/index.ts, packages/core/src/codegen/generateContractTypes.ts, packages/core/src/handlers/handlerQueue.ts, packages/core/src/index.ts, packages/core/src/networks/CachedProvider.ts, packages/core/src/networks/buildNetworks.ts
This PR improves the typing of the `ethers.Contract` objects that are injected into event handlers via the `context` argument. It also makes it so specifying a `blockTag` for contract calls is optional, and ponder will use a default of `event.block.number` (matching the behavior of the contract calls in subgraphs).
- Fixes a bug where contract function return types were mistyped as `bigint` instead of `ethers.BigNumber`
- Limits the contract type to read functions (`stateMutability` either `view` or `pure`)
- Sets a new default `blockTag` of `event.block.timestamp` for contract calls (the `overrides.blockTag` argument is no longer required)
=> Improve contract calls

packages/core/src/db/entity/entityStore.ts, packages/core/src/db/entity/postgresEntityStore.ts, packages/core/src/db/entity/sqliteEntityStore.ts, packages/core/src/db/entity/utils.ts, packages/graphql/src/server/buildPluralField.ts
- Improves generation of filter fields to better match subgraph behavior. Known remaining gaps:
- Relationship fields can now be queried by their ID, but the nested filter field `{fieldName}_: EntityTypeFilter` does not exist (yet)
- Derived field filter fields do not exist
- Fixes related to the handling of filter fields, especially for booleans, null, and undefined
=> Improve GQL filtering

packages/graphql/src/index.ts
This should make it easier to publish to PaaS (i.e. Railway) without extra config.
=> spin up on PORT, fall back to 42069

packages/core/src/db/entity/postgresEntityStore.ts, packages/core/src/db/entity/sqliteEntityStore.ts, packages/core/src/db/entity/utils.ts
This PR extends the changes in https://github.com/0xOlias/ponder/pull/46 to use the postgres bound parameter syntax of `$1`, `$2` vs the SQLite syntax of `?`, `?`. Also a tiny refactor of the surrounding code.
I manually verified that these methods work locally. Need more automated testing for this type of thing 🙃 
cc @holic
=> Fix entity store extra quotations and small refactor

packages/core/src/indexer/queues/blockFrontfillQueue.ts, packages/core/src/indexer/queues/logBackfillQueue.ts
Should fix issue #73 - note I was not able to get the tests running properly so I'm not certain, but should be a good starting point.
Essentially `toHexString()` converts a `BigNumber` to a padded bytes string of fixed length, where `utils.hexValue` converts them to a quantity and strips leading zeros.
=> Resolve leading zeros issue #73

.changeset/kind-clocks-report.md, packages/core/src/Ponder.ts, packages/core/src/db/cache/cacheStore.ts, packages/core/src/db/cache/postgresCacheStore.ts, packages/core/src/db/cache/sqliteCacheStore.ts, packages/core/src/db/cache/utils.ts, packages/core/src/handlers/decodeLog.ts, packages/core/src/handlers/handlerQueue.ts, packages/core/src/indexer/tasks/getLogs.ts, packages/core/src/types.ts, packages/core/src/ui/HandlersBar.tsx, packages/core/src/ui/app.tsx, packages/core/test/basic.test.ts, packages/core/test/ens.test.ts
Updates cache store schema to store all 4 topics in separate columns
Updates `getLogs` to only query for and process logs that the user has registered a handler for 
Fixes #25
=> Only process logs if a handler has been registered

.changeset/tough-months-sleep.md, docs/pages/guides/production.mdx, packages/core/src/Ponder.ts, packages/core/src/server/Server.ts
This PR adds a healthcheck path at `/health`. That path will respond with a 200 if either of the following are true:
1. The backfill is complete and all logs fetched during the backfill have been processed
2. 4.5 minutes have passed since the app started
If neither of these conditions are met, `/health` will respond with a 503. This should enable zero downtime deployments on most cloud platforms. See #24 for more details.
Fixes #24
=> Healthchecks

packages/core/src/Ponder.ts, packages/core/src/codegen/buildEntityTypes.ts, packages/core/src/schema/buildSchema.ts, packages/core/src/schema/readGraphqlSchema.ts, packages/core/src/schema/types.ts, packages/core/src/schema/utils.ts, packages/core/src/server/graphql/buildEntityType.ts
This PR fixes a bug where generated entity types were incorrect. It also improves dev error logging for schema errors.
For a given schema:
```graphql
type MyEntity @entity {
id: ID!
string: String
nonNullString: String!
stringList: [String]
nonNullStringList: [String!]
stringNonNullList: [String]!
nonNullStringNonNullList: [String!]!
}
```
Before:
```ts
export type GobbledArtInstance = {
id: string;
string?: string;
nonNullString: string;
stringList?: string[];
nonNullStringList: string[];
stringNonNullList: string[];
nonNullStringNonNullList: string[];
};
```
After:
```ts
export type MyEntityInstance = {
id: string;
string?: string;
nonNullString: string;
stringList?: (string | null)[];
nonNullStringList?: string[];
stringNonNullList: (string | null)[];
nonNullStringNonNullList: …
```
=> Fix entity type gen

.changeset/shy-wombats-invite.md, packages/core/src/Ponder.ts, packages/core/src/bin/ponder.ts, packages/core/src/common/utils.ts, packages/core/src/db/entity/entityStore.ts, packages/core/src/db/entity/postgresEntityStore.ts, packages/core/src/db/entity/sqliteEntityStore.ts, packages/core/src/handlers/handlerQueue.ts, packages/core/src/schema/buildSchema.ts, packages/core/src/schema/types.ts, packages/core/src/server/Server.ts, packages/core/src/server/graphql/buildEntityType.ts, packages/core/src/server/graphql/buildPluralField.ts, packages/core/test/basic.test.ts, packages/core/test/ens.test.ts
This PR adds an "instance ID" to entity table names, which should fix a bug with zero-downtime deployments and enable multiple Ponder apps that use the same entity names to share the same database (like the same app deployed to both a testnet and mainnet).
It also improves the graceful shutdown behavior (cleans up entity tables).
=> Fix zero downtime deployment bug & improve graceful shutdown 

.changeset/curvy-otters-begin.md, .changeset/stupid-baboons-check.md, packages/core/src/schema/buildSchema.ts, packages/create-ponder/package.json, packages/create-ponder/src/bin/create-ponder.ts, packages/create-ponder/src/common.ts, packages/create-ponder/src/helpers/git.ts, packages/create-ponder/src/helpers/validateGraphProtocolSource.ts, packages/create-ponder/src/helpers/wait.ts, packages/create-ponder/src/index.ts, packages/create-ponder/src/templates/basic.ts, packages/create-ponder/src/templates/etherscan.ts, packages/create-ponder/src/templates/hosted-service.ts, packages/create-ponder/src/templates/subgraphId.ts, packages/create-ponder/src/templates/subgraphRepo.ts, packages/create-ponder/test/main.test.ts, pnpm-lock.yaml
This PR adds a new option `--from-subgraph-id` to `create-ponder`. This options accepts a subgraph deployment ID (which is the IPFS CID of the deployment's `subgraph.yaml`) as an argument and bootstraps a new ponder project for that subgraph.
=> Add `create-ponder --from-subgraph-id`

.changeset/cool-berries-press.md, .changeset/weak-bees-push.md, packages/core/src/backfill/BackfillService.ts, packages/core/src/backfill/logBackfillQueue.ts, packages/core/src/config/contracts.ts, packages/core/src/frontfill/FrontfillService.ts, packages/core/test/BackfillService.test.ts, packages/core/test/utils/expectEvents.ts
Fixes #84 
Should make some progress towards #116 but does not fix
=> Update default block range limit calculations & handle `"Log response size exceeded"` errors

.changeset/yellow-fireants-occur.md, docs/pages/api-reference/event-handlers.mdx, docs/pages/api-reference/ponder-config.mdx, packages/core/src/Ponder.ts, packages/core/src/codegen/buildEventTypes.ts, packages/core/src/errors/eventHandler.ts, packages/core/src/handlers/EventHandlerService.ts, packages/core/src/handlers/getStackTrace.ts, packages/core/src/reload/readHandlers.ts, packages/core/test/Ponder/art-gobblers.test.ts, packages/core/test/Ponder/art-gobblers/schema.graphql, packages/core/test/Ponder/art-gobblers/src/index.ts
This PR adds support for a `"setup"` event which gets processed before all log events. This event handler can be used to setup data in the entity store. It can read from contracts, fetch data from a remote source, or insert static data.
```ts
import { ponder } from "@/generated";
ponder.on("setup", async ({ context }) => {
const { MyEntity } = context.entities;
const { MyContract } = context.contracts
const remoteData = await fetch("https://...");
const contractData = await MyContract.method() 
await MyEntity.create({
id: setupData.id,
data: { ...setupData, ...contractData }
});
});
```
Fixes #150, fixes #87
=> Add `"setup"` event

.changeset/neat-shirts-pay.md, .changeset/smart-masks-argue.md, examples/art-gobblers/ponder.config.ts, examples/art-gobblers/tsconfig.json, examples/ethfs/ponder.config.ts, examples/ethfs/tsconfig.json, packages/core/src/config/abi.test.ts, packages/core/src/config/abi.ts, packages/core/src/config/contracts.ts, packages/core/src/config/logFilters.ts, packages/core/src/config/ponderConfig.ts, packages/create-ponder/src/index.ts, packages/create-ponder/src/templates/etherscan.ts, packages/create-ponder/test/main.test.ts
This PR adds support for EIP-1967 proxies in `create-ponder` when using the Etherscan template option. It checks if the specified contract address is a proxy, and if it is, fetches all historical implementation contract ABIs.
=> Support EIP-1967 proxies in `create-ponder`

.changeset/light-penguins-thank.md, packages/core/src/codegen/buildEventTypes.ts
Fixes #178 by setting the name of anonymous event params to `param_${index}`.
=> fix: anonymous event parameter codegen

.changeset/poor-radios-own.md, packages/core/src/Ponder.ts, packages/core/src/handlers/EventHandlerService.ts
This PR Fixes event handling timestamp ranges. Before we were always grabbing the lowest block timestamp for event handling even when there were other blocks with higher timestamp available to process events from. (mostly in case of multiple chains running on the same app).
With this fix: If the minimum cached to timestamp >= backfillCutoffTimestamp, then we set the new toTimestamp to the max value that exists in the DB and continue with fetching events.
=> fix: event handling issue with timestamp

packages/core/src/user-handlers/service.ts, packages/core/src/user-store/postgres/store.ts, packages/core/src/user-store/sqlite/store.ts, packages/core/src/user-store/store.test.ts, packages/core/src/user-store/store.ts
This PR updates the user store to persist every version of every entity that the user inserts/updates/deletes. The versions are marked by timestamp using an `effectiveFrom`/`effectiveTo` range. When querying for entities using `findUnique`/`findMany` (as is done by the GraphQL server), the latest version of each entity will be returned by default.
This unblocks two features:
1. **Time-travel queries** - Using the timestamp argument to `findUnique`/`findMany`, we can add optional arguments to the GraphQL schema that enable users to query the database at a specific timestamp (Note: this is different that Graph Protocol time-travel queries, which only support querying by block height.)
2. **Reorg handling** - In a follow-up PR, I'll add a new method to the user store that reverts the state …
=> Versioned user store

packages/core/src/event-aggregator/service.ts, packages/core/src/event-store/postgres/store.ts, packages/core/src/event-store/sqlite/store.ts, packages/core/src/event-store/store.test.ts, packages/core/src/event-store/store.ts, packages/core/src/historical-sync/service.test.ts, packages/core/src/user-handlers/service.ts
This PR moves the log filter matching code into SQL such that only the logs that the user has registered a handler for will be fetched from the event store. This will reduce memory usage and improve event processing performance.
=> Improve getEventLogs performance

packages/core/src/Ponder.ts, packages/core/src/config/networks.ts, packages/core/src/user-handlers/service.ts, packages/core/src/user-store/postgres/store.ts, packages/core/src/user-store/sqlite/store.ts, packages/core/src/user-store/store.test.ts, packages/core/src/user-store/store.ts, packages/core/src/utils/logger.ts
This PR adds a `revert(timestamp: number)` method to the user store which rolls the database back to the state at the specified timestamp.
It also adds a `handleReorg` method to the user handler service which calls `revert` whenever a reorg is detected.
=> Add reorg support to user store

.changeset/small-emus-hide.md, etc/README.md, etc/docker-monitoring.yml, etc/grafana/dashboards/dashboard.yml, etc/grafana/dashboards/overview.json, etc/grafana/datasources/prometheus.yml, etc/grafana/grafana.ini, etc/prometheus/prometheus.yml, packages/core/package.json, packages/core/src/Ponder.ts, packages/core/src/_test/utils.ts, packages/core/src/historical-sync/service.test.ts, packages/core/src/historical-sync/service.ts, packages/core/src/metrics/service.ts, packages/core/src/realtime-sync/service.test.ts, packages/core/src/realtime-sync/service.ts, packages/core/src/server/service.ts, packages/core/src/utils/timer.ts, pnpm-lock.yaml
This PR adds support for monitoring ponder instances.
- New endpoint at `/metrics` serving a Prometheus client with the metrics listed below
- An `/etc` directory containing Prometheus and Grafana config and a docker compose config file that starts both services, pointing Prometheus at `http://localhost:42069`
- Fixes a bug where `Keep-Alive` HTTP connections were not being terminated properly on process exit
Prometheus client schema (will add more shortly):
```ts
type Metrics = {
ponder_historical_task_total: prometheus.Counter<"network" | "kind">;
ponder_historical_task_failed: prometheus.Counter<"network" | "kind">;
ponder_historical_task_completed: prometheus.Counter<"network" | "kind">;
ponder_historical_rpc_request_duration: prometheus.Histogram<"network" | "method">; …
```
=> Monitoring

.changeset/modern-nails-travel.md, packages/core/src/codegen/buildEntityTypes.ts, packages/core/test/codegen/main.test.ts
Currently, when we define schema field with `Float` of `Float!` it will raise an error like the following:
```
FAIL  test/codegen/main.test.ts > entity types builder > normal entity
Error: TypeScript type not found for scalar: Float
❯ src/codegen/buildEntityTypes.ts:27:25
25|                 const scalarTsType = gqlScalarToTsType[field.scalarTypeName];
26|                 if (!scalarTsType) {
27|                   throw new Error(
|                         ^
28|                     `TypeScript type not found for scalar: ${field.scalarTypeName}`
29|                   );
❯ src/codegen/buildEntityTypes.ts:22:12
❯ Module.buildEntityTypes src/codegen/buildEntityTypes.ts:19:6
❯ test/codegen/main.test.ts:26:20
```
this pull request added the missing `Float` field in the `buildEntityTypes` and …
=> fix: added missing Float scalar in the codegen

.changeset/short-dingos-sip.md, examples/token-erc721/.env.example, examples/token-erc721/.gitignore, examples/token-erc721/README.md, examples/token-erc721/abis/SmolBrain.json, examples/token-erc721/package.json, examples/token-erc721/ponder.config.ts, examples/token-erc721/schema.graphql, examples/token-erc721/src/index.ts, examples/token-erc721/tsconfig.json, packages/core/src/event-store/postgres/format.ts, packages/core/src/event-store/postgres/store.ts, packages/core/src/event-store/sqlite/format.ts, packages/core/src/event-store/sqlite/store.ts, packages/core/src/types/transaction.ts, pnpm-lock.yaml
This PR adds an ERC271 example app for the Smol Brains NFT collection on Arbitrum. I also noticed some RPC provider inconsistencies while testing this out. Specifically, Alchemy seems to rename `transaction.type` to `transaction.arbType` for some bizarre reason. Quicknode works as expected.
I've ran into enough issues related to this specific field that it may be worth making it nullable in the database, but for now I added a default of `"0x0"` so that Alchemy still works.
Also fixed a bug where `block.baseFeePerGas` was assumed to be non-null when formatting event objects coming out of the event store.
=> Add ERC721 example app

.changeset/short-pumpkins-wash.md, packages/create-ponder/src/helpers/getEtherscanChainId.ts, packages/create-ponder/src/templates/etherscan.ts, packages/create-ponder/test/main.test.ts
This PR adds support for `explorer.zora.energy` contract page URLs in `create-ponder`.
**NOTE:** Conduit (the provider Zora is using) uses Blockscout for their explorer, which as of writing does not support the `?module=contract&action=getcontractcreation` endpoint. Without this endpoint, we can't find the contract's `startBlock` to write it into `ponder.config.ts`. This PR refactors the `etherscan` template code slightly to allow for this case.
=> Add support for Zora explorer URLs in `create-ponder`

.changeset/late-birds-scream.md, .changeset/nervous-vans-arrive.md, .changeset/smart-roses-return.md, examples/art-gobblers/package.json, examples/ethfs/package.json, examples/token-erc20/package.json, examples/token-erc721/package.json, packages/core/package.json, packages/core/src/Ponder.ts, packages/core/src/_test/art-gobblers/app.test.ts, packages/core/src/_test/ens/app.test.ts, packages/core/src/_test/setup.ts, packages/core/src/_test/utils.ts, packages/core/src/event-aggregator/service.test.ts, packages/core/src/event-store/store.test.ts, packages/core/src/historical-sync/service.test.ts, packages/core/src/historical-sync/service.ts, packages/core/src/realtime-sync/service.test.ts, packages/core/src/server/service.test.ts, packages/core/src/server/service.ts, packages/core/src/user-handlers/contract.test.ts, packages/core/src/user-handlers/contract.ts, packages/core/src/user-store/store.test.ts, packages/core/src/utils/wait.ts, packages/core/tsconfig.json, packages/create-ponder/package.json, packages/create-ponder/src/index.ts, pnpm-lock.yaml
This PR bumps viem to `1.2.2` and abitype to `0.8.11` for both `@ponder/core` internals and in the development dependencies of projects created using `create-ponder`.
- Fixed a bug where the Ponder server would occasionally fail to start due to a port detection race condition.
=> Bump viem/abitype versions

.changeset/metal-boats-protect.md, packages/core/src/_test/setup.ts, packages/core/src/event-store/postgres/store.ts, packages/core/src/event-store/sqlite/store.ts, packages/core/src/event-store/store.test.ts, packages/core/src/event-store/store.ts, packages/core/src/historical-sync/service.test.ts, packages/core/src/historical-sync/service.ts
Flaky tests made it clear that the historical sync service was occasionally failing to fully merge log filter cached intervals before emitting the `syncComplete` event. This was caused by a race condition. The previous design was relying on the block task worker to merge cached intervals after inserting the new one, which was unsafe because the multiple merge operations could occur at the same time. The fix introduced here adds some logic to the queue worker to merge all intervals on the last task in the queue.
=> Fix historical sync race condition

packages/core/src/Ponder.ts, packages/core/src/_test/art-gobblers/app.test.ts, packages/core/src/_test/ens/app.test.ts, packages/core/src/event-aggregator/service.test.ts, packages/core/src/event-aggregator/service.ts, packages/core/src/event-store/store.test.ts, packages/core/src/historical-sync/service.test.ts, packages/core/src/metrics/service.ts, packages/core/src/realtime-sync/service.test.ts, packages/core/src/server/service.test.ts, packages/core/src/ui/service.ts, packages/core/src/user-handlers/contract.test.ts, packages/core/src/user-handlers/contract.ts, packages/core/src/user-handlers/model.ts, packages/core/src/user-handlers/service.test.ts, packages/core/src/user-handlers/service.ts, packages/core/src/user-store/postgres/store.ts, packages/core/src/user-store/sqlite/store.ts, packages/core/src/user-store/store.test.ts
This PR introduces a test suite for the user handlers service focused on reorg reconciliation.
It also adds a few metrics for the service:
```typescript
type EventHandlerServiceMetrics = {
ponder_handlers_matched_events: prometheus.Gauge<"eventName">;
ponder_handlers_handled_events: prometheus.Gauge<"eventName">;
ponder_handlers_processed_events: prometheus.Gauge<"eventName">;
ponder_handlers_has_error: prometheus.Gauge; // Boolean
ponder_handlers_latest_processed_timestamp: prometheus.Gauge;
}
```
=> Reorg reconciliation tests

.changeset/few-apples-punch.md, packages/core/src/event-store/postgres/migrations.ts, packages/core/src/event-store/postgres/store.ts, packages/core/src/event-store/sqlite/migrations.ts, packages/core/src/event-store/sqlite/store.ts
This PR improves the performance of an internal event store method (`getLogEvents`) quite a lot by adding indexes and restructuring the generated SQL query to take advantage of them.
If curious - the previous approach used `LIKE` operators for matching `address` and `topics` values, which cannot take advantage of column indexes. The new approach compares values directly, adding additional `AND`/`OR` clauses for each address and topic value present in the log filter.
=> Improve SQL query performance

.changeset/few-teachers-run.md, docs/pages/guides/create-update-entities.mdx, examples/token-erc20/src/index.ts, examples/with-docker/src/index.ts, packages/core/src/types/model.ts, packages/core/src/user-store/postgres/store.ts, packages/core/src/user-store/sqlite/store.ts, packages/core/src/user-store/store.test.ts, packages/core/src/user-store/store.ts
This PR updates the entity `update` and `upsert` methods to optionally accept a function for the update object. This is useful for updates that require data from the existing entity, such as balance or counter increments.
=> Add `update`/`upsert` function option

packages/core/src/_test/art-gobblers/app.test.ts, packages/core/src/_test/ens/app.test.ts, packages/core/src/_test/setup.ts, packages/core/src/config/options.ts, packages/core/src/telemetry/detached-flush.test.ts, packages/core/src/telemetry/service.test.ts, packages/core/src/telemetry/service.ts
Updates test setup to never send telemetry events.
Also adds a telemetry context value `isExampleProject` which is set by the `PONDER_TELEMETRY_IS_EXAMPLE_PROJECT` env var. Moving forward, if you're working on Ponder and running the projects in the `examples/` directory on your local device, be sure to include `PONDER_TELEMETRY_IS_EXAMPLE_PROJECT=true` in your `.env.local` so that the telemetry events emitted by that app are marked properly.
Also note that I've updated the Railway shared env to set that as well.
=> Stop emitting telemetry from tests and example projects

.changeset/perfect-mirrors-leave.md, packages/create-ponder/package.json
It seems becase we're not using a correct starter kit name pattern yarn is not detecting the bin from the npm registry.
See https://classic.yarnpkg.com/lang/en/docs/cli/create/
=> refactor: rename create-ponder bin name

.changeset/tender-badgers-invent.md, packages/core/src/user-store/postgres/store.ts, packages/core/src/user-store/sqlite/store.ts, packages/core/src/user-store/store.test.ts
Fixes #336 . Batch createMany() internally to a maximum size of 1000. This fixes a bug where adding too many values with `createMany()` fails. This was between 6000-7000 for me.
=> Create many overflow

.changeset/curly-carpets-agree.md, packages/core/src/server/service.ts
the protocol was always set to `http`. Now it checks if `localhost` then `http` otherwise `https`
=> fix http protocol when visiting graphiql

pnpm-lock.yaml
`pnpm dedupe` deletes all unused deps from the lockfile that might solve some incompatibility issues with different versions of pnpm. This removed 93 packages according to the cli.
https://pnpm.io/cli/dedupe
=> run `pnpm dedupe`

.changeset/three-houses-argue.md, packages/core/src/server/service.ts
This fixes an issue where the localhost ui would return "failed to fetch graphiql"
=> Fix bug where localhost was being incorrectly identified

packages/core/src/schema/schema.test-d.ts, packages/core/src/schema/types.ts
Fixes a bug in the `Infer` type that resolved enums to an array instead of a union of the elements of the array. 
For example, enum resolved to `["ONE", "TWO"]` instead of `"ONE" | "TWO"`
=> Fix bug with inferring enum types

examples/art-gobblers/ponder.config.ts, examples/art-gobblers/ponder.schema.ts, examples/ethfs/ponder.config.ts, examples/ethfs/ponder.schema.ts, examples/factory-llama/ponder.config.ts, examples/factory-llama/ponder.schema.ts, examples/friendtech/ponder.config.ts, examples/friendtech/ponder.schema.ts, examples/token-erc20/ponder.config.ts, examples/token-erc20/ponder.schema.ts, examples/token-erc721/ponder.config.ts, examples/token-erc721/ponder.schema.ts, examples/token-reth/ponder.config.ts, examples/token-reth/ponder.schema.ts, packages/core/src/_test/art-gobblers/app/ponder.config.ts, packages/core/src/_test/art-gobblers/app/ponder.schema.ts, packages/core/src/_test/ens/app/ponder.config.ts, packages/core/src/_test/ens/app/ponder.schema.ts, packages/core/src/build/service.ts, packages/core/src/codegen/service.ts
Use default exports instead of named exports for `ponder.schema.ts` and `ponder.config.ts`
=> Use default exports for schema and config files

packages/core/src/_test/art-gobblers/app/src/index.ts, packages/core/src/build/functions.ts, packages/core/src/indexing/service.ts, packages/core/src/types/ponder.test-d.ts, packages/core/src/types/ponder.ts
Refactor the logic for `ContractName:setup` for a indexing function. Now a setup function will run on each chain the contract is on.
A type-level bug relating to the `network: "mainnet"` shortcut in config was also fixed.
=> Refactor "Contract:setup" indexing function

packages/core/src/bin/ponder.ts, packages/core/src/sync-historical/service.ts
1. Fixed bug where historical sync progress logs continued after the sync is complete
2. Fixed Node version check bug, was previously
Now looks like
=> Fix historical sync logging

packages/core/src/sync-historical/service.ts, packages/core/src/utils/interval.test.ts, packages/core/src/utils/interval.ts
- Fixes bug where progress interval calculations sometimes reported an incorrect checkpoint. This fixes a user-facing issue where the historical sync stalled out, failed to sync all events, but the indexing service continued processing an incomplete history of events.
- Fixes a bug where using `instanceof` to distinguish viem errors was not working properly (maybe due to viem being a peer dep)?
=> Fix historical sync bugs

packages/core/src/indexing/service.ts
Instead of throwing this error`Error: Invariant violation: No abiItemMeta found for Contract:...`, we instead should emit a warning to the console.
=> Fix error when abi doesn't match emitted events

packages/create-ponder/src/helpers/getEtherscanChainId.ts
=> Wrong API breaks the `create` command for Goerli Base

packages/core/src/Ponder.ts, packages/core/src/server/service.test.ts, packages/core/src/server/service.ts, packages/core/src/sync-gateway/service.test.ts, packages/core/src/sync-gateway/service.ts, packages/core/src/sync-historical/service.ts, packages/core/src/sync-realtime/service.ts, packages/core/src/ui/service.ts
- Adds an `/admin/reload` route to the server which will reload all the sync and index data for a specific chain ID
- Adds helper reset methods to services
- `app.use()` -> `app.all()` for custom routing behavior for a single path
- Adds more testing
- Run an example app from `/examples` using `ponder dev`
- After historical sync has completed, reload the state using (replacing the `<CHAIN_ID>` placeholder for your specific chain:
- `curl -X POST "localhost:42069/admin/reload?chainId=<CHAIN_ID>"`
=> Reload sync and index state for a specific chain ID when developing

packages/core/src/config/config.test-d.ts, packages/core/src/config/config.ts, packages/core/src/config/sources.test.ts, packages/core/src/config/sources.ts, packages/core/src/types/ponder.test-d.ts, packages/core/src/types/ponder.ts
- "parameter" property is strictly typed in "factory"
- ".on()" filters down events based on "filter"
- test file cleanups
=> Config type bug fixes

packages/core/src/schema/schema.ts
Reference columns are no longer required to end in the "Id" suffix.
=> Fix schema reference name runtime validation bug

benchmarks/apps/ponder-univ2/ponder.config.ts, benchmarks/apps/ponder-univ2/src/index.ts, examples/feature-factory/ponder.schema.ts, examples/feature-filter/ponder.schema.ts, examples/feature-multichain/ponder.schema.ts, examples/feature-proxy/ponder.schema.ts, examples/project-friendtech/ponder.schema.ts, examples/project-friendtech/src/FriendtechSharesV1.ts, examples/project-uniswap-v3-flash/ponder.schema.ts, examples/reference-erc20/ponder.schema.ts, examples/reference-erc721/ponder.schema.ts, packages/core/src/_test/constants.ts, packages/core/src/config/factories.test.ts, packages/core/src/config/factories.ts, packages/core/src/config/sources.ts, packages/core/src/indexing-store/postgres/store.ts, packages/core/src/indexing-store/sqlite/store.ts, packages/core/src/indexing-store/store.test.ts, packages/core/src/sync-historical/service.test.ts, packages/core/src/sync-historical/service.ts, packages/core/src/sync-realtime/filter.test.ts, packages/core/src/sync-realtime/filter.ts, packages/core/src/sync-realtime/service.test.ts, packages/core/src/sync-store/postgres/format.ts, packages/core/src/sync-store/postgres/store.ts, packages/core/src/sync-store/sqlite/format.ts, packages/core/src/sync-store/sqlite/store.ts, packages/core/src/sync-store/store.test.ts, packages/core/src/types/log.ts
Two main case sensitivity problems were addressed:
- viem decoding returned checksum addresses while ponder was using lowercase
- bytes values were case sensitive
These issues were fixed by:
- internally representing addresses with checksum
- case insensitive comparisons for "bytes" columns
This closes #478 and closes #194
=> Bytes and Address case sensivity

packages/core/src/indexing-store/postgres/store.ts, packages/core/src/indexing-store/sqlite/store.ts, packages/core/src/indexing-store/store.test.ts, packages/core/src/indexing-store/store.ts, packages/core/src/indexing/service.test.ts, packages/core/src/indexing/service.ts, packages/core/src/indexing/transport.ts, packages/core/src/utils/queue.ts
Retry indexing functions three times before stopping the service and displaying the error to the terminal. Internally, uses the same revert() function that reorgs use to reset the state of the indexing-store to what it was before the failed indexing function ran. 
Ponder actions on client no longer need retry logic and instead use this.
=> Indexing function retries

.changeset/serious-rockets-trade.md, .github/workflows/main.yml, docs/pages/docs/api-reference/_meta.ts, docs/pages/docs/api-reference/config.mdx, docs/pages/docs/api-reference/create-ponder.mdx, docs/pages/docs/api-reference/indexing-functions.mdx, docs/pages/docs/api-reference/ponder-cli.mdx, docs/pages/docs/api-reference/schema.mdx, package.json, packages/core/src/_test/e2e/erc20/erc20.test.ts, packages/core/src/_test/e2e/factory/factory.test.ts, packages/core/src/_test/setup.ts, packages/core/src/bin/ponder.ts, packages/core/src/config/options.ts, packages/core/src/server/service.ts, packages/core/src/ui/graphiql.html.ts
- Adds `--hostname, -H` CLI option to override the default hostname of `0.0.0.0`.
- Updates GraphiQL HTML to run queries against `/` rather than attempt to construct a URL (was leading to hostname and port issues).
=> New CLI options, bug fixes

README.md, docs/pages/docs/advanced.mdx, docs/pages/docs/getting-started.mdx, packages/core/README.md
Hey there!
I've been playing with ponder these last few days: love it, it's a great tool! Thanks for all the effort.
Creating this PR with a couple of _issues_ I found in the Docs:
1. On the `Advanced` page, the foundry link was broken. I also moved it to the bottom (as in the submenu)
2. The getting started guide `ponder.config.ts` example use a JSON path directly on the `abi` prop. Updated it to use the import as suggested in `Add Contracts` page.
Happy to tweak it further if needed.
Thanks!
=> docs: Fix foundry link + import ABI the right way 

.changeset/many-boats-boil.md, packages/create-ponder/.gitignore, packages/create-ponder/package.json, packages/create-ponder/src/_test/cli.test.ts, packages/create-ponder/src/etherscan.ts, packages/create-ponder/src/helpers/getGraphProtocolChainId.ts, packages/create-ponder/src/helpers/validateGraphProtocolSource.ts, packages/create-ponder/src/index.ts, packages/create-ponder/src/subgraph.ts, packages/create-ponder/templates/subgraph/_dot_env.local, packages/create-ponder/templates/subgraph/_dot_eslintrc.json, packages/create-ponder/templates/subgraph/_dot_gitignore, packages/create-ponder/templates/subgraph/package.json, packages/create-ponder/templates/subgraph/ponder-env.d.ts, packages/create-ponder/templates/subgraph/ponder.schema.ts, packages/create-ponder/templates/subgraph/tsconfig.json, pnpm-lock.yaml
Pulls subgraph info from ipfs using subgraph ID and generates ponder config and populates ABIs. Doesn't generate schema based on events yet, and doesn't support subgraph factory templates because the factory's child creation logic is in assemblyscript, and not the subgraph configuration itself.
=> create-ponder subgraph ID support on parity with etherscan

packages/core/src/Ponder.ts, packages/core/src/build/functions/parseAst.test.ts, packages/core/src/build/functions/parseAst.ts, packages/core/src/build/functions/test/abi.ts, packages/core/src/build/functions/test/basic.ts, packages/core/src/build/functions/test/helperFunc.ts, packages/core/src/build/functions/test/helperFuncRename.ts, packages/core/src/build/functions/test/ponder-env.d.ts, packages/core/src/build/functions/test/ponder.config.ts, packages/core/src/build/functions/test/ponder.schema.ts, packages/core/src/build/functions/test/renameVar.ts, packages/core/src/build/functions/test/util.ts, packages/core/src/build/service.ts, packages/core/src/indexing/service.test.ts, packages/core/src/indexing/service.ts
Handle helper functions, including in different files. 
When a ORM method (`upsert()`, `findMany()`) is called on variable that is not recognized, all tables in the schema are added to the table access matrix for that method. The most common occurrence of this is if a user were to rename a variable:
```ts
const { Account, TransferEvent: TE } = context.db;
await TE.update({
...
});
```
In this case, the table access would be the same as if `update()` was called on every table in the schema.
=> Advanced Abstract Syntax Tree Parsing

packages/core/src/build/functions/parseAst.test.ts, packages/core/src/build/functions/parseAst.ts, packages/core/src/build/functions/test/helperFunc.ts, packages/core/src/build/functions/test/util.ts
Fixes
```ts
const helper = async ({ event, context} : {event: Event, context: Context}) => {
...
}
ponder.on("Contract:Event", helper);
```
as seen in `main-characters`
=> Fix bug when passing callback to ponder.on

.changeset/selfish-toys-arrive.md, packages/core/src/build/functions/parseAst.test.ts, packages/core/src/build/functions/parseAst.ts, packages/core/src/build/functions/test/helperClass.ts, packages/core/src/build/functions/test/util.ts
```ts
class HelperClass {
async helper({ context }: { event: Event; context: Context }) {
await context.db.Table.upsert({
id: "kyle",
});
}
}
ponder.on("C:Event1", async ({ event, context }) => {
const h = new HelperClass();
await h.helper({ context, event });
});
```
is now handled by Ponder static analysis.
=> Fixes issue with parsing class methods as helper functions

.changeset/slow-adults-decide.md, packages/core/src/build/config/config.ts
=> Fix: `maxHistoricalTaskConcurrency` ignored in config

.changeset/dirty-clocks-wonder.md, .changeset/thick-monkeys-serve.md, packages/core/src/build/config/config.test.ts, packages/core/src/build/config/config.ts, packages/core/src/sync-store/postgres/store.ts, packages/core/src/sync-store/sqlite/store.ts, packages/core/src/sync-store/store.test.ts, packages/core/src/utils/interval.test.ts, packages/core/src/utils/interval.ts
Fixed a rare bug where contracts that specify multiple addresses or use a custom filter with multiple events would not be cached properly during the sync.
=> Fix custom filters

.changeset/dull-laws-eat.md, packages/core/src/sync-store/postgres/encoding.ts, packages/core/src/sync-store/postgres/migrations.ts, packages/core/src/sync-store/sqlite/encoding.ts, packages/core/src/sync-store/sqlite/migrations.ts, packages/core/src/types/eth.ts
Makes sha3uncles column nullable, enabling support for Celo.
=> Make `blocks.sha3uncles` column nullable

.changeset/light-vans-double.md, packages/core/vite.config.ts
On machines with alot of cores minThreads was defaulting to a value larger than maxThreads causing an issue with test setup
=> fix: explicitly set minThreads

.changeset/strong-oranges-change.md, packages/core/src/server/service.ts
the metrics endpoint will crash the process when it 404s because `end` is called multiple times.
=> fix: metrics endpoint crashes when it 404s

.changeset/hip-geckos-glow.md, packages/core/src/sync-store/postgres/store.ts, packages/core/src/sync-store/sqlite/store.ts
This ensures all retrieved logs will have a corresponding block and transaction. This sometimes would cause an error in apps when a reorg occurs because the realtime service is not handling all possible states properly. Eventually, the realtime service will be fixed and restore the invariant, but this is a faster fix.
=> Use inner join in the getLogEvents query

.changeset/red-deers-care.md, packages/core/src/sync-historical/service.test.ts, packages/core/src/sync-historical/service.ts, packages/core/src/sync-realtime/service.test.ts, packages/core/src/sync-realtime/service.ts, packages/core/src/sync-store/postgres/store.ts, packages/core/src/sync-store/sqlite/store.ts, packages/core/src/sync-store/store.test.ts, packages/core/src/sync-store/store.ts
This PR fixes a bug in the internal `getFactoryChildAddresses` method. Previously, the method attempted to paginate on `blockNumber` without setting an `ORDER BY` on that field, leading to duplicate results. This bug went undetected for quite some time, and only caused an actual error in `0.4` when we began inserting logs in bulk during the historical sync, because the bulk upsert query we are now using throws an error if you attempt to insert two logs with the same ID in the same batch.
=> Fix factory logs bug

.changeset/happy-suits-report.md, packages/utils/src/getLogsRetryHelper.ts
Important to note this is for https://blastapi.io and not Blast, the L2 with native yield (backed but not endorsed by Paradigm).
=> Add retry range detection for blast api

.changeset/tiny-knives-yawn.md, .changeset/weak-sheep-care.md, packages/core/src/bin/utils/shutdown.ts, packages/core/src/common/errors.ts, packages/core/src/common/logger.ts, packages/core/src/database/kysely.ts, packages/core/src/indexing-store/historicalStore.test.ts, packages/core/src/indexing-store/historicalStore.ts, packages/core/src/indexing-store/realtimeStore.test.ts, packages/core/src/indexing-store/realtimeStore.ts, packages/core/src/indexing-store/utils/errors.ts, packages/core/src/indexing/service.ts, packages/core/src/utils/print.ts
This PR improves error logging in two key ways:
1. Catches and ignores errors thrown by database methods that run after the database has been killed. This fixes a really annoying bug that caused the dev server to crash
2. Improved common SQL constraint + logic errors using custom error classes and better logging, see screenshots.
=> Fix hot reloading bug

.changeset/forty-rice-dress.md, packages/core/src/sync-historical/service.ts
=> Improve `sync-historical` logs: network name, missing commas

packages/core/src/sync-historical/service.ts, packages/core/src/sync/index.ts, packages/core/src/utils/requestQueue.ts
Consolidate request retry logic and error handling into the request queue.
This fixes a bug where error logs were thrown for eth_getLogs requests that were being correctly parsed.
=> Move getLogs retry logic into request queue for better errors

packages/core/src/sync-historical/service.ts
Fix the issue of duplicate printing of progress log in synchronisation phase
```
9:27:05 AM INFO  historical Sync is 1.9% complete with ~4h 51m 6s remaining (source=HelixLnBridgeV3, network=sepolia)
9:27:05 AM INFO  historical Sync is 16.2% complete with ~39m 25s remaining (source=HelixLnBridgeV3, network=sepolia)
9:27:05 AM INFO  historical Sync is 69.9% complete with ~3m 45s remaining (source=HelixLnBridgeV3, network=sepolia)
9:27:05 AM INFO  historical Sync is 7.7% complete with ~2h 0m 5s remaining (source=HelixLnBridgeV3, network=sepolia)
9:27:05 AM INFO  historical Sync is 24.8% complete with ~22m 55s remaining (source=HelixLnBridgeV3, network=sepolia)
9:27:05 AM INFO  historical Sync is 1.9% complete with ~4h 51m 8s remaining (source=HelixLnBridgeV3, network=zksync-sepolia)
9:27:05 …
```
=> Filter historical logs

.changeset/green-cheetahs-march.md, packages/core/src/sync-realtime/service.test.ts, packages/core/src/sync-realtime/service.ts
Fixes an issue where a rpc with a flake returning a random block before the finalized block would cause an immediate crash. This "deep reorg" now throws an error and goes through the error logic with multiple timeouts and retries
=> fix: retry deep reorgs

.changeset/witty-guests-melt.md, packages/core/src/indexing-store/historical.test.ts, packages/core/src/indexing-store/historical.ts
The "update" branch of the flush function uses `onConflict` to overwrite existing database rows, but when there are no rows besides "id", nothing needs to be updated. Previously this code path was causing an SQL syntax error, now it just exits early.
=> Fixes bug in historical indexing update cache

packages/core/src/index.ts
Export `TransactionReceipt` type from `@ponder/core` package.
Fix an issue where when using `includeTransactionReceipts: true` in `ponder.config.ts`, the type `TransactionReceipt` wasn't being exported leading to `Module '@ponder/core' declares 'TransactionReceipt' locally, but it is not exported.`.
Current workaround is to import this type from `viem`, but as `@ponder/code` provides `Transaction` and `Log`, it should be exported too.
This PR fixes this.
=> chore: Export `TransactionReceipt` type

.changeset/happy-monkeys-beam.md, packages/core/src/common/telemetry.ts
Fired up a new Ponder instance today for testing purposes and left Telemetry enabled; upon checking the application log, found out that the link to the Telemetry documentation was broken. Think the update is worthy given it's an application log; did check all other links within the codebase but found no other broken link. This pull-request fixes it.
=> chore: Broken Telemetry link

package.json
Fix deprecation alert related to Lint CLI options being used in the package.json
> Note: As this affect the main repo', and not a specific package, I've skipped the changeset as I wasn't sure which to choose.
```
DEPRECATED  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚠ The argument --apply is deprecated, it will be removed in the next major release. Use --write instead.
```
=> chore: Lint options

docs/pages/docs/query/api-functions.mdx
Fix incorrect usage of middleware use with Hono.
Current docs example does not work and errors with `Property 'next' does not exist on type 'MiddlewareContext<{ ... }>`.
Hono Middleware Documentation: https://hono.dev/docs/guides/middleware#custom-middleware
=> fix: Hono usage docs

.changeset/nervous-baboons-destroy.md, packages/create-ponder/templates/empty/ponder.config.ts
Fix #720 
Updated default contract address provided on `create-ponder` empty template to be a valid address
=> fix: Invalid default contract address on empty template

docs/pages/docs/query/api-functions.mdx
=> fix: typo in api-functions example in docs

.changeset/thirty-ants-warn.md, docs/pages/docs/api-reference/create-ponder.mdx, packages/create-ponder/src/helpers/getGraphProtocolChainId.ts, packages/create-ponder/src/index.ts, packages/create-ponder/src/subgraph.ts
Hey there, 
I've added in cursory support for alternate subgraph providers, for example Alchemy Subgraph (formerly Satsuma)
I've used the templates format to allow for more graph-compliant spec subgraph providers in the future.
Would love ya'lls feedback on this.
One thing I noticed is the `chainIdByGraphNetwork` values being hard-coded is this possible something we could have as a param passed into the subgraph template so we could build ponder apps for l2s / l3s that are not yet in that file?
=> feat: Implement support for alternative Subgraph providers

.changeset/metal-apes-care.md, packages/core/src/build/configAndIndexingFunctions.test.ts, packages/core/src/build/configAndIndexingFunctions.ts
This PR addresses an issue with the SQLite directory selection process in `packages/core/src/build/configAndIndexingFunctions.ts`. The code has been updated to prefer the `config.database.directory` if it is provided. If the directory is not specified in the configuration, it will fall back to the default directory `{ponderDir}/sqlite`.
- Updated `packages/core/src/build/configAndIndexingFunctions.ts` to use `config.database.directory` if available when setting the SQLite directory.
- Ensured proper resolution of the directory path.
I didn't test this, couldn't figure out how to. Would appreciate your help @kyscott18 @0xOlias.
- https://github.com/ponder-sh/ponder/pull/679
=> fix: SQLite Directory Selection to Prefer Config Directory

.changeset/wise-tomatoes-appear.md, docs/pages/docs/api-reference/ponder-cli.mdx, packages/core/src/bin/ponder.ts
Even though there's [a comment in the code](https://github.com/ponder-sh/ponder/blob/main/packages/core/src/server/service.ts#L216-L218) indicating that the default hostname behavior should adaptively use ipv6 when possible, the default CLI arg prevents this from actually happening in practice. An easy way to verify this is running a simple example project and attempting to navigate to `http://[::1]:42069/health`, which should fail.
This PR updates the default param to be an empty string, which seems to exhibit the intended behavior. 
Tested locally by verifying both normal `http://localhost:4069/health` and `http://[::1]:42069/health` work for one of the example projects.
Note that it's possible to work around this issue by specifying `--hostname ::` when running `ponder start`.
=> fix: ipv6 support by default

.changeset/chatty-steaks-study.md, packages/core/src/sync-historical/index.ts
Fixes some metrics errors that were causing the terminal ui to break by skipping more historical sync intervals
=> Fixes terminal ui errors

.changeset/nine-meals-attend.md, packages/core/src/sync-historical/index.ts, packages/core/src/sync/index.ts
Initializes the value to 0 and then updates it when realtime is started / when realtime is killed
=> fix `ponder_realtime_is_connected` metric

.changeset/bright-bikes-enjoy.md, packages/core/src/sync-realtime/index.ts
The realtime sync functions in two stages, one concurrent stage to extract chain information corresponding to a block such as logs, call traces, transactions, and transaction receipts. This stage does as much filtering as possible but doesn't have access to all factory addresses. 
The next stage is serial, and factory addresses are available. The logs and call traces are re-filtered but transactions and transaction receipts are not. This is causing extra transactions to be added to the database.
I fixed this issues by re-filtering transactions and transaction receipts in the second stage `handleBlock()`.
=> Fix: extra transactions added in realtime

.changeset/tough-tigers-approve.md, packages/core/src/sync/index.ts
This fixes a bug that would result in the progress showing > 100%. This was reported in the telegram a few times.
This is a result of incorrect handling of `finalized` block refetching. The current logic is as follows:
- sync all blocks from `start` to `historicalLast`(minimum of `finalized` and `end`)
- check if `finalized` is stale (last fetched more than 5 mins ago)
- if not stale, enter realtime
- else, re-run this loop
However, `start` should not be used on iterations after the first, because this would lead to blocks being re-synced (they have already been synced on the first iteration) 
The solution was to detect when `localHistoricalSyncGenerator` should skip blocks that have already been synced, by checking `syncProgress.current`. I validated this worked on the …
=> fix: progress >100%

.changeset/friendly-bikes-work.md, packages/core/src/sync-realtime/index.ts
In sync-realtime, added filtering for transactions whose tx receipts need to be fetched. Relates to #1128 issue
=> Fetching receipts only for filters with includeTransactionReceipt: true

.changeset/stupid-cooks-wash.md, packages/core/package.json, packages/core/src/server/index.test.ts, pnpm-lock.yaml
See context here: https://github.com/ponder-sh/ponder/pull/1146
Upstream change to hono/node-server was included @ https://github.com/honojs/node-server/pull/206
This PR bumps the version of hono/node-server to include the upstream change. I also added a test to ensure ipv6 works, which should help avoid future regressions as well!
=> chore: bumping hono/node-server to support ipv6

.changeset/lovely-spies-dance.md, packages/core/src/sync/index.ts
The `disableCache` option is applied out of order. It needs to be run before `historicalSync.start` because this is where the cache is read.
Currently, the `disableCache` option is applied after `historicalSync.start`, causing the cache progress to be recorded, then the cache to be pruned, which would cause the app to start from the wrong spot and eventually events to be missed.
=> fix: `disableCache` running out of order

docs/components/Footer.tsx, docs/pages/blog/0.2.0.mdx
- Corrected the Twitter link in `Footer.tsx` to point to the official Twitter page instead of GitHub.
- Fixed a typo in the documentation (`funtion` -> `function`) in `blog/0.2.0.mdx`.
https://ponder.sh/
=> fix: Correction of Twitter link and typo in documentation

benchmarks/README.md
There is a typo in the word "hander," the correct spelling is "**handler**."
Corrected.
=> Typo Update README.md

.changeset/nine-dolls-run.md, packages/core/src/bin/utils/run.ts
Fixes a reorg related bug that was reported in the telegram. Based on these logs:
1. Reorg detected on chain A at timestamp 10
2. Reorg detected on chain B at timestamp 8
The issue is that the reorg reconciliation was adding rows to the reorg tables. When the second reorg was reconciled, the rows resulting from chain A were duplicated, causing a primary key constraint violation.
Removing the triggers and therefore avoiding adding to the reorg table when reconciling a reorg fixes this.
=> fix: reorg bug

.changeset/proud-pigs-sniff.md, packages/core/src/bin/commands/codegen.ts, packages/core/src/bin/commands/serve.ts, packages/core/src/bin/utils/run.test.ts, packages/core/src/bin/utils/run.ts, packages/core/src/bin/utils/runServer.ts, packages/core/src/build/schema.ts, packages/core/src/build/service.ts, packages/core/src/common/codegen.ts, packages/core/src/graphql/index.test.ts, packages/core/src/graphql/index.ts, packages/core/src/graphql/middleware.test.ts, packages/core/src/graphql/middleware.ts, packages/core/src/server/index.test.ts, packages/core/src/server/index.ts
Before, `buildGraphqlSchema` needed the built `drizzle` object to access the relational config, which was created by `createDatabase`. Now, it only needs the raw `schema` object and builds the relational config manually using helper functions from Drizzle. This decouples the GraphQL schema build from the database build. With that done, it was easy to move the GraphQL schema build from the server/middleware back to the build step.
=> fix: `schema.graphql` codegen

.changeset/violet-guests-obey.md, docs/pages/docs/query/graphql.mdx, packages/core/src/graphql/index.test.ts, packages/core/src/graphql/index.ts
Adds `totalCount` field to GraphQL page type.
Also fixes two bugs that I noticed while implementing this:
- The one-to-many relation query path had a bug where the `orderBy` argument passed to the plural resolver attempted to use the columns of the parent table. Added a test for this, which was failing before the fix.
- The top-level singular resolver was not using dataloader. Now, certain query paths that do self-joins should do one fewer query.
=> GraphQL `totalCount`

.changeset/tasty-otters-flow.md, packages/core/src/graphql/index.test.ts, packages/core/src/graphql/index.ts
See changeset. Note that there are still some cases of ambiguous parsing that we should consider validating against, e.g. if the column names themselves end with any of the where suffixes like `_not`, `_not_in`.
=> fix: graphql snake case bugs

docs/pages/docs/contracts-and-networks.mdx
`factory` property no longer part of contract config or network override, is provided via `address`
=> docs: remove factory mention under contract config overrides

.changeset/lemon-news-teach.md, packages/core/src/sync-realtime/index.ts, packages/core/src/sync/index.ts
Fixes an issues when handling reorgs with a multi chain configuration. This bug occurs when a reorg on one chain caused an event on a different chain to be reverted and never re-run.
1. event occurs on chain A, get handled with an indexing function
2. reorg detected on chain B
3. event on chain A gets reverted, because it is chronologically ahead of the reorg
4. chain B gets reprocessed, but not chain A
=> fix: reorgs with multiple chains causing missing events

.changeset/flat-donkeys-explain.md, packages/core/src/sync-historical/index.ts
Closes #1338 
It appears that most rpcs (excluding alchemy) have a bug where `topics: [["0x..."]]` and `topics: [["0x..."], null, null, null]` return a different response for "eth_getLogs" requests. Ponder began formatting requests in the second shape starting in v0.8.0.
=> fix: malformed "eth_getLogs" request in `sync-historical`

packages/core/src/sync-historical/index.ts, packages/core/src/sync-store/index.test.ts, packages/core/src/sync-store/index.ts, packages/core/src/sync/index.ts
Fixes a bug where duplicate fragments (defining the same block filter twice) would cause Ponder to crash
=> support duplicate fragments

.changeset/warm-coats-tickle.md, packages/core/src/bin/utils/run.ts, packages/core/src/sync/index.ts
Adds logs to help debug (likely) slow getEvents queries.
```
5:58:39 PM DEBUG app        Started using config file: ponder.config.ts
5:58:39 PM INFO  build      Using PGlite database at .ponder/pglite (default)
5:58:39 PM INFO  database   Using database schema 'public'
5:58:40 PM INFO  database   Created tables [account, allowance, transfer_event, approval_event]
5:58:40 PM DEBUG codegen    Wrote new file at ponder-env.d.ts
5:58:40 PM DEBUG codegen    Wrote new file at generated/schema.graphql
5:58:40 PM DEBUG indexing   Using a 512 MB indexing cache
5:58:40 PM INFO  historical Started syncing 'mainnet' with 100% cached
5:58:40 PM INFO  historical Skipped historical sync for 'mainnet' because all blocks are cached.
5:58:40 PM DEBUG sync       Fetched 0 events from the database for a 16m …
```
=> chore: idle debug logs

.changeset/healthy-buckets-swim.md, packages/core/src/_test/setup.ts, packages/core/src/database/index.ts, packages/core/src/utils/pg.ts
Improves test setup so that errors within tests that use Postgres no longer brick the entire Vitest pool (better isolation).
This also includes a prod/runtime change to register an event handler for the pg.Pool `error` event, which prevents pool-level errors from crashing the process with an uncaughtException.
=> chore: improve test setup for pg errors / isolation

docs/pages/docs/contracts-and-networks.mdx
The `mergeAbi` documentation URL was incorrect
=> typo: merge abis url

.changeset/weak-lemons-travel.md, packages/core/src/sync/index.ts
Relates to #1286. This fix handles the future endBlock by considering it as 
```ts
{
number: toHex(end),
hash: "0x",
parentHash: "0x",
timestamp: toHex(maxCheckpoint.blockTimestamp),
} as LightBlock
```
=> feat: future endBlock

.changeset/stale-timers-remain.md, packages/common/src/dedupe.ts, packages/core/src/build/configAndIndexingFunctions.ts, packages/core/src/build/factory.ts, packages/core/src/sync-historical/index.ts, packages/core/src/sync-store/index.test.ts, packages/core/src/sync-store/index.ts
The factory child address logic was not deduplicating its results, leading to `syncLogsDynamic` being called with many duplicate values. This function has some address batching logic, which would cause multiple replica eth_getLogs requests to be made. The resulting logs failed when being inserted into the database.
- factory contract with many duplicated child addresses
=> fix: duplicate logs

.changeset/long-ligers-travel.md, packages/core/src/sync-historical/index.ts, packages/core/src/sync-realtime/index.ts, packages/core/src/utils/rpc.ts
Closes #1197 . Includes the new helper function (`_eth_getBlockReceipts`) and changes to sync-realtime / sync-histroical. This change should lower the number of requests to RPC and CU costs.
=> feat: replacing getTransactionReceipt with getBlockReceipts

.changeset/eleven-onions-itch.md, packages/core/src/sync/events.test.ts, packages/core/src/sync/events.ts
It's possible for decoded values for `string` ABI parameters to contain null characters. Null characters are ignored by almost all software systems, except the postgres `TEXT` data type does not accept them ([context](https://www.commandprompt.com/blog/null-characters-workarounds-arent-good-enough)).
This PR removes null characters from all decoded ABI strings.
Fixes #1378 #1376
=> fix: null bytes

packages/core/src/sync-historical/index.ts, packages/core/src/sync-realtime/index.ts
Adding a check to not process _eth_getBlockReceipts if there are no transaction receipts needed for this block.
=> fix: removing unnecessary _eth_getBlockReceipts requests

.changeset/shaggy-oranges-lie.md, packages/core/src/sync-store/index.ts, packages/core/src/sync/index.test.ts, packages/core/src/sync/index.ts
Relevant commit: https://github.com/ponder-sh/ponder/commit/77b92ef14fa4a0491f04a009cd2158af8f77c656
=> fix: skipped events in historical to realtime handoff

.changeset/orange-roses-enjoy.md, packages/core/src/sync-historical/index.ts, packages/core/src/sync-realtime/index.ts, packages/core/src/sync-store/index.ts, packages/core/src/sync/events.ts, packages/core/src/sync/index.ts
Seems like we had a regression when merging #1342 and #1411
=> fix empty transaction hash in zksync

.changeset/clean-pears-argue.md, packages/core/src/sync-realtime/index.ts
I have an RPC causing errors, but only one of the two code paths for fetching block logs print the error properly, presumably because the `error.stack` is being unset?
```
caused by:
9:49:42 PM WARN  realtime   Retrying 'mainnet' sync after 1 second.
9:49:44 PM WARN  rpc        Failed eth_getLogs request
9:49:44 PM WARN  realtime   Failed to process 'mainnet' block 21682820
caused by:
9:49:44 PM WARN  realtime   Retrying 'mainnet' sync after 1 second.
9:49:46 PM WARN  rpc        Failed eth_getLogs request
9:49:46 PM WARN  realtime   Failed to process 'mainnet' block 21682820
```
```
9:49:24 PM WARN  rpc        Failed eth_getLogs request
9:49:24 PM WARN  realtime   Failed to fetch latest 'mainnet' block
RpcRequestError: RPC Request failed.
URL: https://ethereum-rpc.publicnode.com/{token} …
```
=> fix: don't clear error stack

packages/create-ponder/src/index.ts
When trying to migrate from Uniswap V2 subgraph, got this error: 
Actually, we should use the Deployment ID, not the subgraph ID:
=> fix: clarify subgraph deployment id, not subgraph id

.changeset/three-flowers-think.md, packages/core/src/graphql/index.test.ts, packages/core/src/indexing-store/realtime.test.ts, packages/core/src/utils/pg.ts
closes #1475 
BigInt array parsing from the `node-postgres` driver, when pointed at actual postgres, parses bigint array values incorrectly iff they're above `MAX_SAFE_INTEGER`. This PR adds a failing test to demonstrate that behavior.
To reproduce, checkout the first or second commit on this PR. With `DATABASE_URL` **UNSET** in your `.env.local`, the tests will pass (`pnpm run --filter ponder test src/graphql/index.test.ts`) because it uses pglite. Set `DATABASE_URL` to a local postgres instance and rerun the tests — they will fail with:
```diff
"bigintArray": Array [
"0",
-       "81043282338925483631878461732084420541800751556297842951124152226153187811344",
+       "81043282338925488948964270414290117064232697336223238797682374271791829876736",
],
"bigintArrayNotNull": Array [
"0",
- …
```
=> WIP: bigint array decode against postgres

docs/pages/docs/contracts-and-networks.mdx
Fixed broken link to Call Traces(/docs/call-traces) on Contracts & Networks page(/docs/contracts-and-networks).
=> fix: broken link in docs

.changeset/good-pugs-appear.md, packages/core/src/graphql/index.ts
This error is often thrown when an enum has not been exported from the Ponder schema. This PR updates the error message to make the fix more obvious.
=> chore: improve GraphQL enum not found error message

.changeset/witty-years-study.md, docs/pages/docs/api-reference/ponder-cli.mdx, packages/core/src/bin/commands/dev.ts, packages/core/src/bin/ponder.ts
The live UI feature in dev mode is awesome, but it often makes it difficult to read logs from API and indexing functions when debugging. This PR adds a CLI flag to the dev command that allows you to disable the live UI.
=> feat: add a flag to disable live UI in dev mode

.changeset/eleven-bees-smell.md, packages/core/src/indexing-store/cache.ts, packages/core/src/indexing-store/historical.test.ts
=> fix: indexing store array parsing

.changeset/gold-dolls-sort.md, packages/core/src/bin/utils/run.ts, packages/core/src/database/index.ts, packages/core/src/indexing-store/cache.test.ts, packages/core/src/indexing-store/cache.ts, packages/core/src/indexing-store/historical.test.ts, packages/core/src/indexing-store/historical.ts, packages/core/src/indexing-store/realtime.ts, packages/core/src/internal/metrics.ts
Adds `ponder_indexing_cache_requests_total`, `ponder_indexing_cache_query_duration`, `ponder_indexing_store_queries_total` and `ponder_indexing_store_raw_sql_duration` to metrics.
=> refactor cache metrics

docs/pages/docs/advanced/foundry.mdx
Hi! I fixes a broken link in the `foundry.mdx` file. The outdated link to Foundry's documentation has been updated to the correct URL
=> fix: update broken link foundry.mdx

.changeset/itchy-chairs-share.md, packages/core/src/indexing-store/cache.test.ts, packages/core/src/indexing-store/cache.ts
Fixed a regression where cached indexing data wouldn't get evicted properly when `totalCacheOps < num cache entries`. This would only occur when all or a high percentage of cache operations were inserts and not updates.
=> fix: flush index

.changeset/few-trains-rule.md, packages/core/src/indexing-store/cache.test.ts, packages/core/src/indexing-store/cache.ts
Fixes a bug that occurs when calling `flush()` multiple times for the same batch of events (same transaction). This occurs because the "update" logic creates a temp table and isn't accounting for the case when the temp table already exists.
With this pr, the temp table is only created if not exists and truncated at the end of the function. Another solution would be to drop the temp table at the end of the function and recreate it on every call.
=> fix `flush()` when using raw sql

.changeset/many-dragons-cry.md, packages/core/src/build/index.ts
fix https://github.com/ponder-sh/ponder/issues/1551
check the Hono instance using `instanceof` instead of checking constructor name. 
this allows the devs to use Hono extended instances such as `@hono/zod-openapi` with ponder.
as long as the peer dependency of hono is correctly setup and both the ponder and the devs are using the same Hono package, the check should work.
if we are worrying the devs could using a different package of hono then alternatively  we can loosen up the check like this:
```
if (!(app instanceof Hono || app?.constructor?.name === "Hono")) {
```
wdyt?
=> fix: build script hono instance check

docs/pages/0_6/docs/advanced/foundry.mdx
While reviewing the documentation, I noticed that a link to Foundry's scripting tutorial in the foundry.mdx file was broken. I’ve updated the link to point to the correct location: https://book.getfoundry.sh/guides/scripting-with-solidity#deploying-to-a-local-anvil-instance.
=> docs: update dead link

.changeset/brown-singers-thank.md, packages/core/src/build/pre.ts
This PR changes error message when pg connection parse throws an error.
Error message before:
```
10:14:01 PM ERROR build      Failed build
BuildError: Invalid URL
```
Error message after:
```
8:05:31 AM ERROR build      Failed build
BuildError: Failed to parse database connection string: Invalid URL
```
Resolves #1591
=> fix(core/build): improve db connection string parse error message

docs/pages/docs/query/api-functions.mdx
In the "Reserved routes" section, changed "heatlthchecks" to "**healthchecks**" in the `/ready` route description.
=> docs: Fix typo in /ready route description

docs/pages/docs/api-reference/config.mdx
The docs instruct users to use `--config-file` CLI arg to specify a custom config file but the actual arg is `--config`. This PR fixes it.
=> Fix CLI arg name in config.mdx

.changeset/soft-hats-whisper.md, packages/core/src/graphql/graphiql.html.ts
UNPKG has not been actively maintained and ~~has been down since `Mar 15, 2025`~~ was down from Mar 15, 2025, 2:00 AM and down for 18 hours (https://github.com/unpkg/unpkg/issues/412). Migrating to jsDelivr means a more stable and reliant service.
The PR replaces UNPKG usage with jsDelivr inside `graphql.html`.
=> fix: replace unpkg w/ jsdelivr

packages/core/src/bin/utils/run.ts, packages/core/src/indexing-store/cache.ts, packages/core/src/sync-store/index.ts, packages/core/src/sync/index.ts
Use `setImmediate` to allow for the event loop to be cleared out after compute-heavy work. This has been shown to have more reliable performance and reduce contention.
=> spin eventloop after cpu work

.changeset/modern-icons-draw.md, packages/core/src/sync/index.ts
The function used to merge event generators between all chains (`mergeAsyncGeneratorsWithEventOrder`) already implements a look-ahead mechanism. Ponder is better off using a larger batch of events.
=> don't use async buffer with omnichain ordering

docs/pages/docs/utilities/types.mdx
corrected a mismatch where `context` was referred to as `event` in the comment.
=> docs: fix variable name in Context example

packages/core/src/sync-realtime/index.test.ts, packages/core/src/sync-realtime/index.ts
Refactor the function names in `sync-realtime`.  
- `sync1`: Start syncing the latest block, fetching all event data.
- `sync2`: Finish syncing a block, using child address to filter all events and checking for reorgs or finalization.
Also added a `consecutiveErrors` counter for each step. This allows for retrying deep reorgs up to 10 times , which was previously missing.
=> improve `sync-realtime` robustness

.changeset/curvy-socks-draw.md, packages/core/src/bin/commands/dev.ts, packages/core/src/bin/commands/serve.ts, packages/core/src/bin/commands/start.ts, packages/core/src/build/index.ts, packages/core/src/build/plugin.ts
- Fixed dependency rules between `ponder.config.ts`, `ponder.schema.ts`, and `src/**.ts`. Now all of these can import from each other without issue.
- Fixed dependency rules for `src/api/index.ts`. No imports are allowed from `src/api/index.ts`.
=> improve build robustness

.changeset/twenty-coats-sit.md, packages/core/src/indexing-store/profile.test.ts, packages/core/src/indexing-store/profile.ts, packages/core/src/indexing/index.ts, packages/core/src/indexing/profile.test.ts, packages/core/src/indexing/profile.ts, packages/core/src/internal/types.ts
Closes #1683 
Handles abi items such as:
```solidity
event Paused();
function execute() external;
```
=> fix prediction for logs and traces with no args

benchmarks/src/subgraph.ts, docs/pages/0_6/docs/indexing/read-contract-data.mdx, docs/pages/0_6/docs/schema.mdx
This PR includes the following fixes:
- Corrects spelling of "delimiter" in benchmarks/src/subgraph.ts comment
- Fixes typo "youself" to "yourself" in docs/pages/0_6/docs/indexing/read-contract-data.mdx
- Updates "foriegn" to "foreign" keyword in docs/pages/0_6/docs/schema.mdx
These changes are minor spelling corrections that improve code documentation readability.
=> Fix typos: Correct spelling of "delimiter" and "yourself", update foreign/foreign keyword

.changeset/empty-tips-rush.md, packages/core/src/sync-realtime/index.test.ts, packages/core/src/sync-realtime/index.ts
There is a bug in deep reorg handling because we are:
1) evicting blocks from `unfinalizedBlocks`
2) not throwing a "reorg" event (that would cause db rows to be reverted)
This is a bug because once the chain eventually reconciles, events in evicted blocks are duplicated. I fixed this by making sure that no blocks are evicted when a deep reorg occurs.
=> fixes duplicate event when deep reorg occurs

docs/pages/docs/getting-started/new-project.mdx
just a quick fix in the docs - changed "Ethereum RPC API" to "standard Ethereum JSON-RPC API" to keep things accurate. It's more in line with how Ethereum actually works.
=> docs: fixing incorrect wording for Ethereum JSON-RPC reference

.changeset/curvy-elephants-flow.md, packages/core/src/sync/index.ts
There is a bug in the `sync-realtime` factory logic, causing child addresses to not be written to the database while the corresponding interval is, leading to a corrupted ponder_sync. This causes missed events on the following instances, as reported by several users.
In order to remove only the corrupted cache intervals without dropping the entire ponder_sync schema, drop only factory intervals.
https://github.com/ponder-sh/ponder/blob/d17043f7788edd50ec96543bdfdd1f2db4ccb639/packages/core/src/sync-store/migrations.ts#L1672-L1681
=> fix: realtime sync not properly caching child addresses

packages/core/src/bin/commands/dev.ts, packages/core/src/bin/commands/start.ts, packages/core/src/bin/utils/run.ts, packages/core/src/database/index.test.ts, packages/core/src/database/index.ts, packages/core/src/indexing-store/cache.test.ts, packages/core/src/indexing-store/cache.ts, packages/core/src/indexing-store/historical.test.ts, packages/core/src/sync/index.test.ts, packages/core/src/sync/index.ts
Migrations of the "user" schema now validate the "version" of the `_ponder_meta` table.
https://github.com/ponder-sh/ponder/blob/5a3a2ddc80c550f2c2b6d630ddaf340718d40ccb/packages/core/src/database/index.ts#L104
New instances of Ponder will validate using this version or throw an error. Note that versions <=0.8 will throw the error because the `version` column was added in 0.9.
Also combined the `database.migrate()` and `database.recoverCheckpoint()` function.
=> improve user schema migrations

packages/client/src/index.ts, packages/core/src/_test/e2e/erc20/erc20.test.ts, packages/core/src/_test/e2e/factory/factory.test.ts, packages/core/src/_test/utils.ts, packages/core/src/bin/commands/dev.ts, packages/core/src/bin/commands/list.ts, packages/core/src/bin/commands/prune.ts, packages/core/src/bin/utils/run.ts, packages/core/src/client/index.test.ts, packages/core/src/client/index.ts, packages/core/src/database/index.test.ts, packages/core/src/database/index.ts, packages/core/src/drizzle/kit/index.ts, packages/core/src/graphql/index.test.ts, packages/core/src/graphql/index.ts, packages/core/src/graphql/middleware.ts, packages/core/src/indexing-store/cache.ts, packages/core/src/internal/options.ts, packages/core/src/internal/types.ts, packages/core/src/server/index.test.ts, packages/core/src/server/index.ts, packages/core/src/sync/index.test.ts, packages/core/src/sync/index.ts, packages/core/src/utils/generators.test.ts, packages/core/src/utils/generators.ts
The primary feature this unlocks is multichain ordering during the historical backfill and more precise crash recoveries.
It also improves performance for "finalize" step during historical backfill (we noticed it was longer than expected).
- Replaced `_ponder_status` with `_ponder_checkpoint`
- removed `checkpoint` column from `_ponder_meta`
- `_ponder_checkpoint` has both "latest" and "safe" checkpoint for each chain
- Incremented  user schema `VERSION`  #1649 
https://github.com/ponder-sh/ponder/blob/42e9feec5f9b62fa4dce84f04e334eed30675d4f/packages/core/src/database/index.ts#L135
- Improved performance for "multichain" `getEvents` with better merging algorithm
- multichain crash recovery skips re-extracting events when possible
- added `is_ready` column to `_ponder_meta`
- added index …
=> New `_ponder_checkpoint` table with support for multiple chains

.changeset/little-pillows-push.md, packages/core/src/indexing-store/historical.test.ts, packages/core/src/indexing-store/historical.ts, packages/core/src/indexing-store/index.ts, packages/core/src/indexing-store/realtime.test.ts, packages/core/src/indexing-store/realtime.ts
Add validations so that primary keys cannot be updated in `db.update().set` and `db.insert().values().onConflictDoUpdate()`
=> Add primary key update validation

examples/reference-erc20/src/index.ts
When a user is newly added, their balance should start at `amount` as they are given that from the event
=> fix: ERC20 example produces incorrect balances

docs/pages/docs/config/chains.mdx
Fixes a type error in the chain config's custom transport example - there is no `transport` field, it's just `rpc`, which also accepts a `Transform` type value.
=> docs: fix type error in custom transport example

docs/vocs.config.tsx
Fixes the "Suggest changes" deep link at the bottom of each page in the docs. It appears the `vocs` directory was renamed to `docs` in the repo at some point.
=> docs: fix "Suggest changes" deep link

packages/utils/src/_test/aurora.test.ts, packages/utils/src/_test/harmony.test.ts, packages/utils/src/_test/moonriver.test.ts, packages/utils/src/getLogsRetryHelper.ts
Adds Harmony, Moonriver, and Aurora RPC support to `getLogsRetryHelper`.
When these RPCs return block range errors, the helper now extracts the limit and
automatically chunks requests accordingly:
- **Harmony**: _"query must be smaller than size X"_ (limit: 1024)
- **Moonriver**: _"block range is too wide (maximum X)"_ (limit: 1024)
- **Aurora**: _"up to a X block range"_ (limit: 2000)
Includes tests to verify the new functionality works as expected for all three
chains.
=> feat: support Harmony, Moonriver, and Aurora retry ranges

.changeset/cute-points-rush.md, packages/core/src/bin/commands/createViews.ts, packages/core/src/bin/utils/run.ts
#1894 introduced a regression when creating a view for a `_ponder_checkpoint` table that previously had `chain_id` of type `INTEGER`.
=> fix view creation

packages/core/src/sync/index.ts
There is no need to sort out events into pending and waiting for other chains' realtime, since the event execution order is not guaranteed to be sequential across chains in multichain ordering. 
If you have two chains, A and B and their timeline in checkpoint terms as follows: 
A:   -------------------------------------|(finalized A)--------------------|(latest)|
B:   --------------|(finalized B)|-------------------------------------------|(latest)|
Currently, the events for chain A between finalized A and finalized B checkpoints are sorted out to be pending, since there is a need for realtime behavior on chain B. This is only valid for omnichain. 
In multichain, we can fearlessly execute those events and do not wait for chain B to switch to realtime. This pr adds this condition.
=> fix: no pending sorting on multichain ordering

integration-test/src/index.ts, packages/core/src/bin/utils/run.ts, packages/core/src/rpc/index.ts, packages/core/src/sync-realtime/index.test.ts, packages/core/src/sync-realtime/index.ts, packages/core/src/sync/index.test.ts, packages/core/src/sync/index.ts, packages/core/src/utils/generators.test.ts, packages/core/src/utils/generators.ts, packages/core/src/utils/mutex.ts
Update several functions in the realtime sync pipeline to use async generators rather than callbacks.
```ts
type Sync = {
// ... other properties (including "getHistoricalEvents")
getRealtimeEvents: () => AsyncGenerator<RealtimeEvent>;
}
type SyncRealtime = {
// ... other properties
sync: () => AsyncGenerator<RealtimeSyncEvent>;
}
```
=> refactor realtime sync pipeline to use async generator pattern

.changeset/stale-impalas-hope.md, packages/core/src/utils/decodeAbiParameters.ts, packages/core/src/utils/decodeEventLog.test.ts, packages/core/src/utils/decodeEventLog.ts
Copies viem `decodeEventLog` tests. Fixes same bug as fixed here https://github.com/wevm/viem/commit/d88a55b8f41c928767f1cbc2fa82d04e4ca9e3a3
=> add `decodeEventLog` tests
