packages/core/src/db/entity/postgresEntityStore.ts
packages/core/src/db/entity/sqliteEntityStore.ts

We don't need no Little Bobby Tables spilling our milk

migrate get/insert/update/upsert calls to SQL parameters

---

.changeset/breezy-pumpkins-glow.md
examples/art-gobblers/abis/ArtGobblers.json
examples/ethfs/abis/FileStore.json
packages/core/src/common/logger.ts
packages/core/src/handlers/decodeLog.ts
packages/core/src/handlers/handlerQueue.ts

Fixes #36 
Also fixed some ABI formatting and a bug where the ponder logger would not respect the PONDER_LOG_LEVEL env var

Support partial ABIs

---

.changeset/dull-zebras-suffer.md
packages/core/package.json
packages/core/src/Ponder.ts
packages/core/test/basic.test.ts
pnpm-lock.yaml

Fix file watching on linux

---

docs/pages/getting-started/migrate-subgraph.mdx

Just a small typo, was confusing me a bit

fix: small typo in migrate-subgraph.mdx

---

packages/graphql/src/server/index.ts

feat(graphql): redirect / to /graphql

---

.changeset/tiny-news-pump.md
packages/core/src/server/ServerService.ts
packages/core/src/ui/app.tsx
packages/core/test/Ponder/art-gobblers.test.ts
packages/core/test/Ponder/ens.test.ts
packages/create-ponder/src/templates/etherscan.ts

feat: change graphql api path from /graphql to /

---

packages/core/src/Ponder.ts
packages/core/src/_test/art-gobblers/app.test.ts
packages/core/src/_test/art-gobblers/app/ponder.config.ts
packages/core/src/_test/ens/app.test.ts
packages/core/src/_test/setup.ts
packages/core/src/event-aggregator/service.test.ts
packages/core/src/event-aggregator/service.ts
packages/core/src/event-store/postgres/store.ts
packages/core/src/event-store/sqlite/store.ts
packages/core/src/event-store/store.test.ts
packages/core/src/handlers/EventHandlerService.ts
packages/core/src/historical-sync/service.test.ts
packages/core/src/historical-sync/service.ts
packages/core/src/realtime-sync/service.test.ts
packages/core/src/realtime-sync/service.ts
packages/core/src/schema/schema.test.ts
packages/core/src/schema/schema.ts
packages/core/src/schema/types.ts
packages/core/src/server/graphql/buildEntityType.ts
packages/core/src/server/graphql/buildPluralField.ts
packages/core/src/server/graphql/buildSingularField.ts
packages/core/src/user-store/postgres/store.ts
packages/core/src/user-store/sqlite/store.ts
packages/core/src/user-store/store.test.ts
packages/core/src/user-store/store.ts
packages/core/src/user-store/utils.ts

Known issues with this:
- Comparisons (including sorting) on fields typed as `BigInt` will not work (BigInts are being stored as `TEXT` in both databases)
- `findMany` tests are very incomplete
- Unrelated to this PR but for 0.1.0:
- Injected contracts are broken
- The CLI UI is broken
- Still no pagination on events being fetched by the event handler service from the event aggregation service

New user store

---

examples/ethfs/ponder.config.ts
packages/core/src/Ponder.ts
packages/core/src/_test/setup.ts
packages/core/src/_test/utils.ts
packages/core/src/event-store/migration.test.ts
packages/core/src/historical-sync/service.test.ts
packages/core/src/historical-sync/service.ts
packages/core/src/metrics/service.ts
packages/core/src/realtime-sync/service.test.ts
packages/core/src/realtime-sync/service.ts
packages/core/src/server/service.test.ts
packages/core/src/server/service.ts
packages/core/src/ui/HistoricalBar.tsx
packages/core/src/ui/app.tsx
packages/core/src/ui/service.ts
packages/core/src/user-handlers/service.test.ts
packages/core/src/utils/timer.ts

- Adds HTTP metrics to the server
- Adds connection metrics to the realtime and historical sync services (useful for TUI)
- Adds periodic `info`-level logs to the historical sync process to improve the initial prod backfill experience
- Updates the default Grafana dashboard to include various new metrics

Metrics refresh

---

.changeset/fuzzy-planes-obey.md
packages/core/src/Ponder.ts
packages/core/src/_test/constants.ts
packages/core/src/build/handlers.ts
packages/core/src/build/service.ts
packages/core/src/codegen/event.ts
packages/core/src/config/abi.test.ts
packages/core/src/config/abi.ts
packages/core/src/config/logFilters.ts
packages/core/src/event-aggregator/service.ts
packages/core/src/event-store/postgres/store.ts
packages/core/src/event-store/sqlite/store.ts
packages/core/src/event-store/store.test.ts
packages/core/src/event-store/store.ts
packages/core/src/user-handlers/service.test.ts
packages/core/src/user-handlers/service.ts
packages/core/src/utils/duplicates.ts
packages/core/src/utils/range.ts

Support overloaded event names

---

.changeset/old-ducks-listen.md
packages/core/src/Ponder.ts
packages/core/src/event-aggregator/service.test.ts
packages/core/src/event-aggregator/service.ts
packages/core/src/event-store/postgres/store.ts
packages/core/src/event-store/sqlite/store.ts
packages/core/src/event-store/store.test.ts
packages/core/src/event-store/store.ts
packages/core/src/historical-sync/service.test.ts
packages/core/src/ui/HandlersBar.tsx
packages/core/src/user-handlers/service.test.ts
packages/core/src/user-handlers/service.ts
packages/core/src/utils/date.ts

Add pagination to internal event queries

---

.prettierignore
README.md
benchmarks/docker-compose.yml
benchmarks/subgraph/package.json
docs/package.json
docs/pages/_app.mdx
docs/pages/api-reference/create-ponder.mdx
docs/pages/api-reference/event-handlers.mdx
docs/pages/api-reference/ponder-config.mdx
docs/pages/getting-started/migrate-subgraph.mdx
docs/pages/getting-started/new-project.mdx
docs/pages/guides/create-update-entities.mdx
docs/pages/guides/design-your-schema.mdx
docs/pages/guides/logging.mdx
docs/pages/guides/production.mdx
docs/pages/index.mdx
docs/style.css
package.json
packages/core/README.md
packages/create-ponder/README.md
pnpm-lock.yaml

- Bump pnpm to `8.6.10`
- Add git pre-commit hooks using `simple-git-hooks` and `lint-staged`
- Add prettierignore to play nice with lint hook
- Bump nextra to `2.10.0` and next to `13.x` (fixed the docs build)

Repo chores

---

docs/package.json
docs/pages/api/telemetry/index.ts
pnpm-lock.yaml

add API handler to forward payload to Segment

---

.changeset/swift-eyes-repeat.md
packages/core/src/types/model.ts
packages/core/src/user-handlers/model.ts
packages/core/src/user-store/store.ts

Also adds missing string `contains` filter condition

Add `createMany` and `updateMany` to public type

---

packages/core/package.json
packages/create-ponder/package.json

same setup as wagmi
https://github.com/wagmi-dev/wagmi/blob/7e9785410ed2dad5a080b2baeec990e58a63c9ab/packages/core/package.json#L6-L10

add repo info to pkg json

---

.gitignore
.prettierignore
.vscode/extensions.json
.vscode/settings.json
docs/pages/index.mdx

update eslint vscode settings

---

packages/core/src/Ponder.ts
packages/core/src/_test/art-gobblers/app.test.ts
packages/core/src/_test/ens/app.test.ts
packages/core/src/bin/ponder.ts
packages/core/src/build/config.ts
packages/core/src/config/contracts.ts
packages/core/src/config/database.ts
packages/core/src/config/logFilters.ts
packages/core/src/config/networks.ts
packages/core/src/config/options.ts
packages/core/src/config/types.ts
packages/core/src/index.ts

Because this file is in the build step, it should be in the `build/` folder. Also sets the repo up for the adjacent function `buildSchema()`

Move config build to build/

---

.changeset/loud-days-perform.md
packages/core/src/Ponder.ts
packages/core/src/_test/globalSetup.ts
packages/core/src/_test/setup.ts
packages/core/src/event-store/postgres/migrations.test.ts
packages/core/src/event-store/sqlite/migrations.test.ts
packages/core/src/server/service.test.ts
packages/core/src/user-store/postgres/store.ts
packages/core/src/user-store/sqlite/store.ts
packages/core/src/user-store/store.test.ts
packages/core/src/user-store/store.ts

Fixes #220 (finally!)
Also fixes CI.

Fix the stale table bug

---

examples/art-gobblers/ponder.config.ts
examples/ethfs/ponder.config.ts
examples/factory-llama/ponder.config.ts
examples/friendtech/ponder.config.ts
examples/token-erc20/ponder.config.ts
examples/token-erc721/ponder.config.ts
examples/token-reth/ponder.config.ts
packages/core/src/Ponder.ts
packages/core/src/_test/art-gobblers/app/ponder.config.ts
packages/core/src/_test/ens/app/ponder.config.ts
packages/core/src/config/config.test-d.ts
packages/core/src/config/config.ts
packages/core/src/config/networks.ts
packages/core/src/config/sources.test.ts
packages/core/src/config/sources.ts
packages/core/src/indexing/service.test.ts
packages/core/src/indexing/service.ts
packages/core/src/types/ponder.test-d.ts
packages/core/src/types/ponder.ts

Use object keys instead of arrays in createConfig() argument.

Use objects keys in createConfig() argument

---

packages/core/src/Ponder.ts

Revert "Add await keywords to promise all when killing ponder"

---

packages/create-ponder/src/etherscan.ts
packages/create-ponder/src/index.ts

Fixes some etherscan contract link template bugs I found while verifying #458

Create ponder fixes

---

.github/workflows/main.yml

Actions will timeout after 3 minutes

Actions timeout

---

packages/core/src/build/functions.ts
packages/core/src/indexing-store/postgres/store.ts
packages/core/src/indexing-store/sqlite/store.ts
packages/core/src/indexing/service.ts

Also fixes small bug where the app would crash if there was a contract with no indexing functions registered.

Fix versioning race condition

---

packages/core/src/Ponder.ts
packages/core/src/build/service.ts
packages/core/src/config/validate.ts

Build and validate config, schema, and indexing functions up front. Improves startup speed and user feedback loop.

Refactor build pipeline

---

packages/core/src/build/service.ts
packages/core/src/config/networks.ts
packages/core/src/config/validate.ts
packages/core/src/schema/validate.ts

More descriptive errors on validating schema and config

---

.changeset/ten-bats-lie.md
packages/core/src/Ponder.ts
packages/core/src/build/service.ts
packages/core/src/sync-realtime/service.ts
packages/core/src/utils/queue.ts

Fixes multiple small issues relating to:
- memory usage in the queue
- file watcher listening to generated files
- sync services startup errors

Fix minor bugs in build service, queue, and sync services

---

.changeset/gold-peas-fix.md
packages/create-ponder/src/index.ts

Fix create-ponder when passing etherscan link from cli

---

.changeset/five-rings-deny.md
packages/core/src/Ponder.ts
packages/core/src/bin/ponder.ts

Fix codegen command

---

packages/core/src/types/ponder.ts

ponder is a work of art, this is another stroke on the canvas

Prettify types of log, block, transaction

---

packages/core/src/indexing/service.ts
packages/core/src/sync-store/postgres/store.ts
packages/core/src/sync-store/sqlite/store.ts
packages/core/src/utils/checkpoint.ts

Remove the selfDependentLock, and cleanup some algorithms as well as add comments.

Indexing service refinement

---

packages/core/src/indexing/service.ts

Dynamic task batch size and debug log for indexing function dependencies

Indexing Small Nits

---

.changeset/rotten-geese-report.md
packages/core/src/sync-store/postgres/format.ts
packages/core/src/sync-store/postgres/migrations.ts
packages/core/src/sync-store/sqlite/format.ts
packages/core/src/sync-store/sqlite/migrations.ts
packages/core/src/types/block.ts

Make `block.mixHash` and `block.nonce` columns nullable

---

.changeset/thirty-lies-brake.md
packages/core/package.json
packages/core/src/build/service.ts
pnpm-lock.yaml

Path aliases

---

.changeset/rotten-lamps-relax.md
.vscode/settings.json
packages/core/src/Ponder.ts
packages/core/src/metrics/service.ts
packages/core/src/sync-realtime/filter.test.ts
packages/core/src/sync-realtime/filter.ts
packages/core/src/sync-realtime/format.ts
packages/core/src/sync-realtime/service.test.ts
packages/core/src/sync-realtime/service.ts

Refactor realtime sync service to use less rpc credits under all scenarios.
Closes #228.

Efficient Realtime Sync

---

.changeset/gentle-bulldogs-double.md
.changeset/mighty-cups-hammer.md
packages/core/src/indexing-store/postgres/store.ts
packages/core/src/indexing-store/sqlite/store.ts
packages/core/src/indexing-store/store.test.ts
packages/core/src/indexing-store/utils/cursor.ts
packages/core/src/indexing-store/utils/filter.test.ts
packages/core/src/indexing-store/utils/filter.ts
packages/core/src/indexing-store/utils/sort.test.ts
packages/core/src/indexing-store/utils/sort.ts

Fix `findMany` bugs

---

.changeset/long-cups-grow.md
packages/core/package.json
pnpm-lock.yaml

upgrade ast-grep to fix docker compatibility

---

.changeset/giant-deers-burn.md
packages/core/src/indexing-store/postgres/store.ts
packages/core/src/indexing-store/sqlite/store.ts
packages/core/src/indexing-store/store.test.ts
packages/core/src/indexing-store/utils/sort.test.ts
packages/core/src/indexing-store/utils/sort.ts

Fix before pagination

---

.changeset/friendly-olives-brush.md
packages/core/src/config/database.ts

fix: sqlite `filename` config value was ignored

---

.changeset/many-games-serve.md
packages/core/src/indexing-store/postgres/store.ts
packages/core/src/indexing-store/sqlite/store.ts
packages/core/src/indexing-store/store.test.ts

Improve store errors

---

.changeset/metal-roses-smash.md
.changeset/purple-cherries-invite.md
packages/core/src/Ponder.ts
packages/core/src/_test/utils.ts
packages/core/src/build/service.ts
packages/core/src/sync-historical/service.ts

Endblock + build service fix

---

.changeset/tough-terms-smash.md
packages/create-ponder/package.json
pnpm-lock.yaml

Adds a handful of `viem/chains` including Blast

Upgrade viem in create-ponder

---

.changeset/tiny-feet-thank.md
packages/core/src/sync-store/postgres/encoding.ts
packages/core/src/sync-store/postgres/migrations.ts
packages/core/src/sync-store/sqlite/encoding.ts
packages/core/src/sync-store/sqlite/migrations.ts
packages/core/src/types/eth.ts

Drop not null constraint for r, s, and v

---

.changeset/stupid-rockets-provide.md
packages/core/src/sync-realtime/service.test.ts
packages/core/src/sync-realtime/service.ts

Also fixes logs for block not found and fixed a potential bug with reorg reconciliation

Adds retry delay with exponential backoff

---

.changeset/poor-rockets-tap.md
packages/core/src/sync-historical/service.ts
packages/core/src/sync-realtime/service.ts
packages/utils/src/_test/utils.ts

another day another javascript footgun

Fix eth_getLogs not properly being retried

---

packages/utils/src/_test/zksync.test.ts
packages/utils/src/getLogsRetryHelper.ts

add zksync url to retry ranges

---

.changeset/tame-zoos-thank.md
packages/core/src/build/config/config.ts
packages/core/src/build/functions/functions.ts
packages/core/src/build/schema/schema.ts
packages/core/src/sync-realtime/service.ts

Fix initial build error logging

---

packages/core/src/bin/commands/dev.ts
packages/core/src/common/metrics.ts
packages/core/src/sync-historical/service.ts
packages/core/src/ui/Table.tsx
packages/core/src/ui/app.tsx
packages/core/src/ui/service.ts

Improve TUI

---

.changeset/little-walls-buy.md
.changeset/weak-coins-press.md
.changeset/young-pots-compete.md
packages/core/src/sync-store/postgres/store.ts
packages/core/src/sync-store/sqlite/store.ts
packages/core/src/sync-store/store.test.ts

This PR fixes two factory contract bugs, see changeset for details.
Fixes https://github.com/ponder-sh/ponder/issues/794

fix: factory sync checkpoint upsert

---

.changeset/hungry-points-turn.md
packages/core/src/sync-store/postgres/encoding.ts
packages/core/src/sync-store/postgres/migrations.ts
packages/core/src/sync-store/sqlite/encoding.ts
packages/core/src/sync-store/sqlite/migrations.ts
packages/core/src/sync-store/sqlite/store.ts
packages/core/src/types/eth.ts

Dropped null constraint on blocks table

---

.changeset/dull-rockets-film.md
packages/core/src/sync-store/sqlite/migrations.ts

Fix SQLite block nullable columns

---

.changeset/sour-poems-dance.md
docs/pages/docs/advanced/logging.mdx
packages/core/src/_test/setup.ts
packages/core/src/bin/commands/codegen.ts
packages/core/src/bin/commands/dev.ts
packages/core/src/bin/commands/serve.ts
packages/core/src/bin/commands/start.ts
packages/core/src/bin/utils/shutdown.ts
packages/core/src/common/common.ts
packages/core/src/common/logger.ts
packages/core/src/common/telemetry.test.ts
packages/core/src/common/telemetry.ts

See changeset.
Follow up TODOs:
- Figure out how to get ink + pino working nicely together 
- Add configuration options for structured vs pretty logs

Fix logger memory bug

---

.changeset/cyan-pants-begin.md
packages/core/src/sync-store/postgres/store.ts
packages/core/src/sync-store/sqlite/store.ts

Revert "feat: checkpoint selecting strategy on sync-store getEvents"

---

docs/pages/docs/query/graphql.mdx

I was reading through the docs and noticed a minor typo. This PR fixes that.
Thanks for this amazing project btw <3

fix minor typo in graphql query docs

---

examples/feature-blocks/ponder-env.d.ts
examples/feature-call-traces/ponder-env.d.ts
examples/feature-factory/ponder-env.d.ts
examples/feature-filter/ponder-env.d.ts
examples/feature-multichain/ponder-env.d.ts
examples/feature-proxy/ponder-env.d.ts
examples/feature-read-contract/ponder-env.d.ts
examples/project-friendtech/ponder-env.d.ts
examples/project-uniswap-v3-flash/ponder-env.d.ts
examples/reference-erc1155/ponder-env.d.ts
examples/reference-erc20/ponder-env.d.ts
examples/reference-erc4626/ponder-env.d.ts
examples/reference-erc721/ponder-env.d.ts
examples/with-foundry/ponder/ponder-env.d.ts
examples/with-nextjs/ponder/ponder-env.d.ts
packages/core/src/common/codegen.ts
packages/create-ponder/templates/empty/ponder-env.d.ts
packages/create-ponder/templates/etherscan/ponder-env.d.ts
packages/create-ponder/templates/subgraph/ponder-env.d.ts

Closes https://github.com/ponder-sh/ponder/issues/949

Fix link to docs in all examples

---

.changeset/yellow-points-try.md
packages/core/src/schema/schema.test-d.ts
packages/core/src/schema/schema.ts

fix: p.many bug with self references

---

.changeset/cold-weeks-breathe.md
packages/core/src/build/configAndIndexingFunctions.ts

Enforce minimum polling interval

---

.changeset/fresh-shirts-cry.md
packages/core/src/server/service.test.ts
packages/core/src/server/service.ts

Relevant https://blog.cloudflare.com/how-cloudflare-runs-prometheus-at-scale

fix: metric label cardinality explosion

---

.changeset/eight-fans-flash.md
packages/core/src/utils/format.ts

fix: #1022

---

packages/core/src/sync-store/index.ts

- moved filter insert outside of the loop
- moved transaction inside of the loop

cleanup `getIntervals`

---

.changeset/honest-knives-smell.md
packages/core/src/build/service.ts

e.g. for:
```ts
export default createConfig({
networks: {
mainnet: { chainId: 1, transport: http(process.env.PONDER_RPC_URL_MAINNET) },
},
contracts: {
'FooToken': {
abi: ERC721,
address: "0x1231231231231231231231231231231231231231",
network: "mainnet",
startBlock: 11111111,
filter: {
event: "Transfer",
args: {
tokenId: [1n, 2n, 3n],
},
},
},
},
})
```

Serialize config with BigInts

---

.changeset/tasty-lies-sneeze.md
packages/core/src/sync-historical/index.ts
packages/core/src/sync-realtime/index.ts
packages/core/src/sync-store/index.test.ts
packages/core/src/sync-store/index.ts
packages/core/src/sync/index.ts

Fixes a bug causing out of order events when a contract is used as both a normal contract and a factory.
Closes #1067

Fix out of order factory events

---

docs/pages/docs/utilities/types.mdx

Fix import on `docs/utility/types`

---

docs/pages/docs/utilities/types.mdx

Fix imports from docs https://ponder.sh/docs/utilities/types

Fix utility types imports

---

.github/actions/setup/action.yml
packages/core/src/common/telemetry.test.ts

Pin to 9/2/2024 release (https://github.com/foundry-rs/foundry/releases/tag/nightly-d75318c9c7a1c6af5404fe96f63ca890dcdd588d)
Also attempts to fix our telemetry flake

Pin foundry toolchain version

---

.changeset/rare-panthers-march.md
packages/core/src/sync/fragments.test.ts
packages/core/src/sync/fragments.ts
packages/core/src/sync/index.test.ts

fix: build fragment for factories with multiple addresses

---

packages/core/src/bin/utils/run.ts

fix edge case leading to negative estimate in ui

---

.changeset/eight-dogs-cover.md
packages/core/src/bin/utils/run.ts
packages/core/src/sync/index.ts

fix status containing unindexed blocks

---

.changeset/stale-numbers-approve.md
packages/core/src/sync-realtime/filter.test.ts
packages/core/src/sync-realtime/filter.ts
packages/core/src/sync/index.ts

fix: realtime filtering with factory lists of addresses

---

.changeset/blue-cooks-decide.md
examples/feature-multichain/ponder-env.d.ts
packages/core/src/indexing-store/historical.ts

Improved the performance of large `updateMany()` operations by ~5x

optimize `updateMany`

---

.changeset/forty-maps-draw.md
packages/core/src/sync-historical/index.ts

fix bug leading to transaction being undefined in indexing functions

---

.changeset/olive-lions-boil.md
packages/core/src/utils/requestQueue.ts

more aggressively retry rpc errors

---

packages/core/src/sync-historical/index.ts
packages/core/src/sync/source.ts
packages/core/src/utils/debug.ts
packages/core/src/utils/rpc.ts

Added syncTrace function in sync-historical with transfer and transaction filter matching.

sync historical

---

packages/core/src/_test/setup.ts
packages/core/src/build/plugin.ts
packages/core/src/build/service.ts
packages/core/src/drizzle/index.ts

Addresses https://t.me/ponder_sh/7662
Not certain this will fix it because the virtual module method was working locally as well.

replace @/generated shim with global variable

---

packages/core/src/bin/commands/codegen.ts
packages/core/src/bin/commands/dev.ts
packages/core/src/bin/commands/serve.ts
packages/core/src/bin/commands/start.ts
packages/core/src/build/index.ts
packages/core/src/build/service.ts

Provides a more long term solution to the problem fixed in https://github.com/ponder-sh/ponder/commit/160d1e2f9742304ed169acc5e3e6c23f35be094c

simplify dev server

---

packages/core/src/common/options.ts

feat: use more accurate cache size

---

docs/pages/docs/production/deploy.mdx

"You app will have performance issues"
There is a typo in the phrase: it should be "**Your**" instead of "You".
Correct version: "Your app will have performance issues".
Corrected.

Typo Update deploy.mdx

---

.changeset/long-queens-end.md
packages/core/src/database/index.ts
packages/core/src/drizzle/kit/index.ts

- Fixed a bug when using `onchainSchema()`

fix: `onchainSchema` creating undefined schema

---

.changeset/silver-owls-buy.md
.changeset/swift-oranges-wink.md
packages/core/src/build/service.ts
packages/core/src/database/index.test.ts
packages/core/src/database/index.ts

Fixed more errors with `onchainSchema()` specifically with pglite. Also fixed an issue with `build_id`, causing it to be incorrect because it was including the `instance_id`

fix: more `onchainSchema()`

---

.changeset/cyan-buses-nail.md
packages/core/src/indexing-store/historical.ts

fix: `flush()` with null values

---

.changeset/gentle-donkeys-hammer.md
packages/core/src/database/index.ts

fix: cleanup old tables

---

.changeset/famous-files-grab.md
.changeset/neat-rice-help.md
packages/core/src/indexing-store/historical.test.ts
packages/core/src/indexing-store/historical.ts
packages/core/src/indexing-store/realtime.test.ts
packages/core/src/indexing-store/realtime.ts
packages/core/src/types/db.test-d.ts
packages/core/src/types/db.ts

fix: value returned by realtime store

---

.changeset/shaggy-carrots-boil.md
packages/core/package.json
packages/core/src/database/index.ts
packages/core/src/indexing-store/historical.ts
pnpm-lock.yaml

Revert `flush()` with copy statement

---

.changeset/pretty-beers-watch.md
packages/core/src/graphql/index.test.ts
packages/core/src/graphql/index.ts

fix: enum primary key

---

docs/pages/docs/accounts.mdx

fix: account name typo in accounts readme

---

.changeset/six-toys-deliver.md
packages/core/package.json
pnpm-lock.yaml

Attempting to fix #1366 and #1386

pin pglite

---

.changeset/itchy-eels-double.md
packages/core/src/sync-historical/index.test.ts
packages/core/src/sync-historical/index.ts
packages/core/src/sync-store/index.test.ts
packages/core/src/sync-store/index.ts
packages/core/src/sync/fragments.test.ts
packages/core/src/sync/fragments.ts
packages/core/src/sync/index.ts
packages/core/src/sync/source.ts
packages/core/src/utils/interval.ts

Revert "Granular `sync-historical`"

---

.changeset/chilly-pigs-shake.md
packages/core/src/sync-historical/index.ts
packages/core/src/sync-realtime/index.ts
packages/core/src/sync/events.ts

fix: zkSync system logs

---

packages/core/src/_test/setup.ts
packages/core/src/bin/commands/dev.ts
packages/core/src/bin/commands/list.ts
packages/core/src/bin/commands/serve.ts
packages/core/src/bin/commands/start.ts
packages/core/src/bin/utils/run.test.ts
packages/core/src/build/index.ts
packages/core/src/build/plugin.ts
packages/core/src/client/index.ts
packages/core/src/database/index.test.ts
packages/core/src/database/index.ts
packages/core/src/drizzle/onchain.ts
packages/core/src/internal/types.ts
packages/core/src/types.d.ts

```ts
// src/api/index.ts
import { clients } from "ponder:api";
```
Feels like there might be a better name than `clients`

inject clients into api file

---

packages/core/src/bin/utils/run.ts
packages/core/src/sync/index.test.ts
packages/core/src/sync/index.ts

Fixes a bug that was introduced in 0.9.3. This bug causes decoding errors for apps with multiple chains that don't have the same sources for each chain. 
This is because `getEvents()` marks each event with a `sourceIndex` property to designate which source was matched for the given event. `decodeEvents()` then uses this `sourceIndex` property to recover the source and abi, and decode the event arguments. `getEvents()` and `decodeEvents()` were not receiving the same `sources` argument, which causes an error when trying to decode.

fix: decoding error when different chains have different sources

---

.changeset/green-dodos-wave.md
packages/core/src/sync/index.ts

fix: missing realtime events

---

.changeset/shaggy-actors-rhyme.md
.changeset/violet-points-enjoy.md
packages/core/src/bin/utils/run.ts
packages/core/src/sync/index.ts

fix: seconds metrics with crash recovery

---

.changeset/soft-singers-type.md
packages/core/src/indexing-store/cache.ts
packages/core/src/indexing-store/historical.test.ts

fix: handle null values with db.update

---

.changeset/cyan-books-burn.md
packages/core/src/indexing-store/cache.test.ts
packages/core/src/indexing-store/cache.ts

fix: indexing cache using stale values

---

.changeset/clean-olives-jump.md
packages/core/src/sync-historical/index.ts

fix: local dev with foundry

---

.changeset/slow-ways-walk.md
packages/core/src/graphql/index.test.ts
packages/core/src/graphql/index.ts

fix: graphql null equality

---

.changeset/twelve-planes-perform.md
packages/core/src/graphql/index.ts
packages/core/src/index.test.ts
packages/core/src/indexing-store/cache.ts
packages/core/src/indexing-store/realtime.ts
packages/core/src/indexing-store/utils.ts

fix: `ponder` entrypoint includes node.js imports

---

packages/core/src/build/index.ts

Hey all - ran into this link which caused a warning from the browser, updated it to the current docs link

fix: fix outdated link in CLI

---

.changeset/shiny-poets-cheat.md
docs/pages/docs/api-reference/schema.mdx
docs/pages/docs/schema.mdx
packages/core/src/drizzle/bytes.ts
packages/core/src/drizzle/onchain.ts
packages/core/src/graphql/index.test.ts
packages/core/src/indexing-store/historical.test.ts
packages/core/src/indexing-store/realtime.test.ts

add `bytes()` column type

---

.changeset/slow-donkeys-love.md
packages/core/src/database/index.test.ts
packages/core/src/database/index.ts

Implement `revert()` in SQL

---

docs/pages/0_6/docs/query/api-functions.mdx
docs/pages/0_6/docs/utilities/replace-bigints.mdx
docs/pages/docs/indexing/read-contract-data.mdx

This pull request contains changes to improve clarity, correctness and structure.

fix: typos in documentation files

---

.changeset/loud-knives-beg.md
packages/core/src/indexing-store/historical.ts

Clear indexing cache after raw sql

---

.changeset/witty-bears-appear.md
packages/core/src/build/index.ts
packages/core/src/drizzle/onchain.ts
packages/core/src/drizzle/text.ts
packages/core/src/indexing-store/historical.test.ts
packages/core/src/indexing-store/realtime.test.ts
packages/core/src/sync-store/encoding.ts
packages/core/src/sync/events.test.ts
packages/core/src/sync/events.ts

Fix null bytes behavior

---

.changeset/sour-stingrays-fry.md
packages/core/src/bin/utils/run.ts
packages/core/src/internal/metrics.ts
packages/core/src/sync-store/index.ts
packages/core/src/sync/events.ts
packages/core/src/sync/index.ts

Added `ponder_historical_concurrency_group_duration`, `ponder_historical_extract_duration`, `ponder_historical_transform_duration` metrics.

performance metrics

---

.changeset/famous-pigs-drop.md
docs/pages/docs/api-reference/ponder-cli.mdx
packages/core/src/bin/commands/list.ts
packages/core/src/bin/commands/prune.ts
packages/core/src/bin/commands/start.ts
packages/core/src/bin/ponder.ts
packages/core/src/bin/utils/exit.ts
packages/core/src/database/index.ts
packages/core/src/internal/options.ts

Also fixed a bug for `ponder db list` when there was only one schema in the database

add `ponder db prune` command

---

.changeset/cyan-forks-decide.md
packages/core/src/sync/transport.ts

Fix `client.multicall()` for viem >= 2.23.7

fix `client.multicall()`

---

.changeset/light-owls-judge.md
packages/core/src/bin/utils/run.ts
packages/core/src/database/index.ts
packages/core/src/indexing-store/access.ts
packages/core/src/indexing-store/cache.test.ts
packages/core/src/indexing-store/cache.ts
packages/core/src/indexing-store/historical.test.ts
packages/core/src/indexing-store/historical.ts
packages/core/src/indexing-store/index.ts
packages/core/src/indexing-store/profile.test.ts
packages/core/src/indexing-store/profile.ts
packages/core/src/indexing-store/realtime.ts
packages/core/src/indexing/index.ts
packages/core/src/internal/options.ts

Improve the indexing store performance by recording historical cache accesses and using the data to prediction future accesses.

indexing store prediction

---

.changeset/fifty-moose-speak.md
packages/core/src/build/schema.test.ts
packages/core/src/build/schema.ts

add validation for duplicate table names

---

.changeset/forty-worms-yell.md
examples/with-offchain/offchain/package.json
examples/with-offchain/ponder/package.json
packages/client/package.json
packages/core/package.json
pnpm-lock.yaml

update `drizzle-orm` to `v0.41.0`

---

.changeset/empty-ghosts-poke.md
packages/core/src/client/validate.ts

Relates to #1668. Fixes the findMany and findFirst queries by adding the "json_build_array" sql function into allowed functions.

fix: relational query

---

.changeset/empty-ghosts-poke.md
packages/core/src/client/validate.ts

Revert "fix: relational query"

---

.changeset/curvy-lizards-prove.md
packages/core/src/graphql/index.test.ts
packages/core/src/graphql/index.ts

Fix: GraphQL `many` relations resolver

---

package.json
packages/core/src/utils/rpc.ts
pnpm-lock.yaml
vocs/styles.css

This fixed at least one case of the import sorting issue I have.

chore: upgrade biome

---

.changeset/ninety-pears-promise.md
packages/core/src/graphql/index.test.ts
packages/core/src/graphql/index.ts

fix: one -> many relations

---

.changeset/rare-moons-fry.md
packages/core/src/drizzle/onchain.ts
packages/core/src/index.ts

fix `ponder.schema.ts` type errors

---

.changeset/six-heads-post.md
packages/core/src/internal/metrics.ts

Reference: https://github.com/ponder-sh/ponder/commit/f1231b3cd108cf5e380b47c118863be27bbb4467

fix dev ui for truncated events

---

.changeset/rich-cities-press.md
packages/core/src/database/index.ts
packages/core/src/internal/logger.ts
packages/core/src/sync-store/migrations.ts

Moved migration logs to debug level

fix: move 0.10 migration logs to debug level

---

.changeset/five-garlics-do.md
packages/core/src/sync-store/index.test.ts
packages/core/src/sync-store/index.ts
packages/core/src/sync/index.ts

Crash recovery checkpoint is resolved per chain via db introspection.

fix: crash recovery checkpoint

---

.changeset/slow-dryers-rescue.md
packages/core/src/utils/rpc.ts

Fix logsBloom check with empty logs response

Fix empty logs error check

---

.changeset/silent-paths-mate.md
.github/workflows/single-integration-test.yml
packages/core/src/_test/setup.ts
packages/core/src/bin/commands/createViews.ts
packages/core/src/bin/commands/dev.ts
packages/core/src/bin/commands/list.ts
packages/core/src/bin/commands/prune.ts
packages/core/src/bin/commands/serve.ts
packages/core/src/bin/commands/start.ts
packages/core/src/bin/utils/run.ts
packages/core/src/database/index.test.ts
packages/core/src/database/index.ts
packages/core/src/drizzle/kit/index.ts
packages/core/src/sync/index.ts

Fixed the reorg behavior for multichain ordering both for databse and sync.

Fix: reorg revert on multichain

---

.changeset/spotty-eels-grow.md
packages/core/src/internal/metrics.ts

Used time weighted sliding window to improve the eta prediction on the ui.

Improve the eta prediction on the ui

---

.changeset/wicked-taxes-burn.md
packages/core/src/graphql/index.test.ts
packages/core/src/utils/serialize.ts

fix https://github.com/ponder-sh/ponder/issues/1879 by converting date objects into a special format, and deserialize them back to date correctly

fix: serialize and deserialize date field correctly to and from cursor

---

.changeset/clever-foxes-matter.md
packages/core/src/build/factory.test.ts
packages/core/src/build/factory.ts
packages/core/src/config/address.test-d.ts
packages/core/src/config/address.ts
packages/core/src/utils/offset.test.ts
packages/core/src/utils/offset.ts

This introduces an ability to specify the parameter for a factory within a struct. Relates to #1323 .

feat: factory event `parameter` within struct

---

.changeset/chilly-baths-lick.md
packages/core/src/sync-store/index.ts

fix: insert rpc requests

---

packages/core/src/bin/commands/codegen.ts
packages/core/src/bin/commands/createViews.ts
packages/core/src/bin/commands/dev.ts
packages/core/src/bin/commands/list.ts
packages/core/src/bin/commands/prune.ts
packages/core/src/bin/commands/serve.ts
packages/core/src/bin/commands/start.ts
packages/core/src/bin/utils/exit.ts
packages/core/src/bin/utils/run.ts
packages/core/src/database/queryBuilder.ts
packages/core/src/indexing/index.test.ts
packages/core/src/indexing/index.ts
packages/core/src/internal/errors.ts
packages/core/src/rpc/index.ts
packages/core/src/sync-historical/index.test.ts
packages/core/src/sync-historical/index.ts
packages/core/src/sync-realtime/index.test.ts
packages/core/src/sync-realtime/index.ts
packages/core/src/sync/index.test.ts
packages/core/src/sync/index.ts

Consider retryable vs non-retryable errors when deciding exit code

improve error handling

---

packages/core/src/rpc/index.ts

Debounces the errors such that only the rejection handler is engaged and not onError callback on the subscription request failure.

fix: websocket error handling

---

.changeset/rare-jeans-crash.md
packages/core/src/indexing/client.ts

fix context.client types

---

.changeset/few-jeans-stay.md
packages/utils/src/_test/ankr-tac.test.ts
packages/utils/src/getLogsRetryHelper.ts

fix ankr tac eth_getLogs

---

.changeset/slimy-feet-smile.md
packages/core/src/indexing/client.ts
packages/core/src/indexing/profile.test.ts
packages/core/src/indexing/profile.ts
packages/core/src/utils/dedupe.ts

Closes https://t.me/pondersh/14590

fix `context.client` prefetching when `cache: "immutable"`

---

.changeset/violet-clocks-show.md
packages/core/package.json
packages/core/src/rpc/index.ts
pnpm-lock.yaml

Adds a websocket client built directly on `ws` rather than relying on `viem` websocket client.

custom websocket client

---

packages/core/src/rpc/index.ts
packages/core/src/runtime/realtime.ts
packages/core/src/sync-realtime/index.ts

- tweaked RPC load balancing parameters to be more resilient to 429 and timeout errors
- improved `sync-realtime` concurrency
- increased `MAX_QUEUED_BLOCKS` to 50

Improve realtime latency
